### ISSUE TITLE
Upgrade six to >=1.12.0 in casa-dev images

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#10]
These images will be upgraded:

- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] `windows-7-64`

Other images will be deprecated / abandoned.

**Comment by ylep** [comment]
Hi @sapetnioc, did you finish to build the Windows images with the new `six`?

**Comment by sapetnioc** [comment]
No, it failed. And I put it low on the TODO list...
