### ISSUE TITLE
Image RecipeBuilder should allow setting environment variables

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#114]
For example it is useful to set LANG to C.UTF-8 in order to correctly handle accented filenames. The Dockerfile used to contain these lines:

https://github.com/brainvisa/casa-distro/blob/621d1c45d89a94ee7d8332be5c855eaf22143fea/share/docker/casa-run/ubuntu-18.04/Dockerfile#L3-L4

**Comment by sapetnioc** [comment]
I would not put env var definition in the `build_image.py` because it is not so easy to implement with VirutalBox. For dev image, we use an `environment.sh` file. I propose that we use the same method to define env vars in run image.

**Comment by denisri** [comment]
Anyway currently the image is using an ASCII locale, and some BrainVisa processes cause failures because of that (which is not very good I admit), so this needs an urgent fix.
Can we create the file `environment.sh` in the run image, then overwrite it in the dev image ?

**Comment by sapetnioc** [comment]
We discussed that point with @ylep some days ago. We believe that it is best to have two files with different names in run and dev images. For instance, it could be `environment.sh` for run image and `dev_environment.sh` for dev image. But I misunderstood this commit. It is about adding environment in the file that is generated to build Singularity images. So this is something internal to image building system and is not related to environment variables we want to set for end users.

**Comment by denisri** [comment]
Then it is two separate issues. I am speaking about variables for users.

**Comment by ylep** [comment]
@denisri Well we thought that a cleaner solution might be to set that environment variable directly in the Singularity `casa-run` image (through the image build script). This way it will be set both during the build, and for users.

One issue if we put it in `environment.sh` is that it will also affect the VirtualBox images, which are likely using a different locale (`en_US.utf-8` I presume).

**Comment by denisri** [comment]
So that's not what has been said here before ;)
I don't know how to set it in images...
Doesn't the locale depend on the system image (ubuntu variant/settings) rather than on the virtualization system ? (or is it really what we want, because having VirtualBox behave differently from singularity is not what we expect)
Well I'm afraid we need this fixed very soon (not to say: _now_) because people are stuck with errors in the processings.

**Comment by denisri** [comment]
I have implemeneted the `environment.sh` solution for now because I was not aware of this discussion and I need a quick fix for that. We can go back on it later.
