### ISSUE TITLE
Create a CEA distro

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#116]

**Comment by denisri** [comment]
Should any Cati components (such as catidb) be part of the "CEA" distro ? And if yes, which ones ?

**Comment by sapetnioc** [comment]
I don't think so. There will be a specific distro for CATI.
CEA distro is for components to be used internally in Neurospin, MirCEN and
SHFJ.

**Comment by denisri** [comment]
Ok then I think the cea distro is ready.
