### ISSUE TITLE
New 'bv' command for end users

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#119]
We decided to introduce a new `bv` command / family of commands, which will be the entry point for end users. Developers keep using `casa_distro`, the release team keeps using `casa_distro_admin`.

The new command(s) provide the functionality that are currently provided by `casa_distro setup`, `casa_distro run`, and `casa_distro shell`.

We could have for example:
- `bv` for running a command in the container (e.g. `bv anatomist`, `bv brainvisa`) (equivalent to `casa_distro run`)
- ~`bv-install` for the initial setup (equivalent to `casa_distro setup`)~ (to be discussed in #144)

Ideally these commands should have the usual syntax of Unix command-lines (`argparse`-style), instead of the `key=value` style that `casa_distro` has used historically.

**Comment by ylep** [comment]
- sheer `bv-install`: interactive prompt presenting the list of versions available on brainvisa.info, the version(s) that are currently installed, and proposing to install the latest version by default
- `bv-install download brainvisa-5.0` / `bv-install download brainvisa` (latest)
- `bv-install list`
- `bv-install remove brainvisa-5.0`

**Comment by ylep** [comment]
- plain `bv` without options: launches the launcher/container configuration interface (https://github.com/brainvisa/casa-distro/issues/80)
- `bv command` launches the command in the Singularity container (e.g. `bv brainvisa`)
- `bv` is not used at all in the VirtualBox workflow (rather, the user downloads the VirtualBox image and does everything inside of VirtualBox)

**Comment by ylep** [comment]
`bv` will completely replace `casa_distro run` for end users. They will be able to put it in the `PATH` (along with the wrapper scripts for `brainvisa`, `anatomist`, `Aims...`)

`bv` shall only be able to work with the environment that it is part of: it will not have knowledge of a casa-distro repository. Its implementation should be entirely self-contained in a new `casa_distro.bv` sub-package.

`bv` will be installed during `casa_distro setup` in `<environmen_dir>/bin` or `<environment_dir>/host/hostbin`, and `<environment_dir>/python`.

**Comment by sapetnioc** [comment]
I did a first implementation of the bv command. It does not do many things except finding `casa_distro` command, finding execution environment and then calling a command with `casa_distro run`. Here is how it works :

- The `bv` command is distributed with casa-distro. Therefore, it uses `sys.argv[0]` (after resolving symlinks) to find `casa_distro` command. If not possible, it is searched in `PATH`.

- `bv` command can be symlinked (better) or copied in a specific casa-distro environement in `<environment_dir>/bin/bv`. In that case `<environment_dir>` is used to select the environment where to run the command.

- If `bv` is located outside an environment. It can run if `CASA_ENVIRONMENT_DIR` is set to a valid environment (i.e. an environment listed in `casa_ditro list`) or if there is only one environment configured in `casa_distro list`.

- `bv` simply calls `casa_distro run` in the selected environment to run a given command. If no command is given, a default one starting a configuration gui is used. To date it is `python -m casa_distro.configuration_gui` but it wil very likely be modified see #80.
