### ISSUE TITLE
casa-distro depends on wget

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#120]
wget is not installed on many host machines (windows, mac, even some linuxes). We should at least document this additional dependency, or replace it with some more widely used tool (curl ?), or provide an alternative python-only solution (but which will probably not handle error recovery).

**Comment by denisri** [comment]
curl seems to be installed on MacOS 10.15 without brew.

**Comment by denisri** [comment]
but curl is not installed on all linuxes, and especially not in casa-distro images...

**Comment by sapetnioc** [comment]
In order to avoid a depency, we can use singularityand DockerHub to get the appropriate command. For instance :

```
singularity pull --disable-cache wget docker://mwendler/wget
./wget -h

singularity pull --disable-cache curl docker://curlimages/curl
./curl -h
```

Both images are very small (a few Mb).

**Comment by denisri** [comment]
`singularity pull --disable-cache` does not work for me (ubuntu 16.04 + singularity 3.6.2).
It works as expected if I don't use `--disable-cache`, and if I set this option, the output file is not written in the current directory  (as expected and documented), but I can find an image in `/tmp/sbuild-tmp-cache-<number>`.
In computers you can never rely on an expected behaviour...

**Comment by denisri** [comment]
BTW, can singularity images be executed as `./wget -h` on any system (including windows ?) or must we use `singularity run ./wget` ?

**Comment by sapetnioc** [comment]
I have exactly the same behavior with singularity 3.6.1 on Windows. I wanted to finish to test the whole instructions before providing an updated workflow but I am still stuck on image creation.

Technically we are never on Windows. I run Singularity on Ubuntu 18.04 installed on a Windows file system and using a Linux kernel running on Windows (that is my understanding of WSL2). Therefore all programs work almost exactly as on "bare metal" Linux. When I discovered the possibility to execute a Singularity image I hoped to release casa_distro that way to remove all dependencies (I thought singularity was included in images). But it uses a shebang therefore singularity must be installed and in the PATH. I believe shebangs work on Mac. Any way, in the code I'd rather call `singularity run` explicitely.
