### ISSUE TITLE
Make the 3.0 branch PEP8 and flake8-clean

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#129]
We currently have very basic [flake8](https://flake8.pycqa.org/) checks that catch only obvious errors. Should we take the opportunity of the refactoring that we are doing in the 3.0 branch, and make the whole code PEP8 and flake8 clean?

Below are the statistics of errors in the current version (2461d8b3a2bcdffa51161a82405274d0b61860cd). We have a lot of indentation warnings, trailing whitespace, which will make a large diff and cause merge conflicts if other people edit the code in parellel. 

Therefore, @sapetnioc  @denisri @Hboni can you confirm that you are okay with enforcing PEP8 on casa-distro, and tell me if you have pending changes that you need to commit beforehand? Then I will go ahead and run `autopep8`, fixing the remaining issues by hand.

Of course, if we want to maintain the code quality then we should all enable pre-commit by running `pre-commit install` in our clones of the repository :slightly_smiling_face: 

```
17      E111 indentation is not a multiple of four
15      E114 indentation is not a multiple of four (comment)
86      E116 unexpected indentation (comment)
2       E124 closing bracket does not match visual indentation
1       E125 continuation line with same indent as next logical line
25      E127 continuation line over-indented for visual indent
84      E128 continuation line under-indented for visual indent
3       E129 visually indented line with same indent as next logical line
8       E201 whitespace after '['
9       E202 whitespace before '}'
1       E203 whitespace before ','
1       E221 multiple spaces before operator
12      E225 missing whitespace around operator
19      E227 missing whitespace around bitwise or shift operator
47      E231 missing whitespace after ','
31      E251 unexpected spaces around keyword / parameter equals
9       E261 at least two spaces before inline comment
1       E262 inline comment should start with '# '
147     E265 block comment should start with '# '
9       E301 expected 1 blank line, found 0
59      E302 expected 2 blank lines, found 1
24      E303 too many blank lines (2)
4       E401 multiple imports on one line
6       E402 module level import not at top of file
231     E501 line too long (216 > 79 characters)
9       E502 the backslash is redundant between brackets
8       E701 multiple statements on one line (colon)
4       E731 do not assign a lambda expression, use a def
68      F401 'glob' imported but unused
3       F821 undefined name 'unicode'
14      F841 local variable 'e' is assigned to but never used
107     W291 trailing whitespace
149     W293 blank line contains whitespace
9       W391 blank line at end of file
8       W503 line break before binary operator
```

**Comment by sapetnioc** [comment]
My various repositories are synced with 3.0 branch. It is ok for me to make the PEP8 change.

**Comment by denisri** [comment]
I've just pushed my last modifs. OK then.

**Comment by Hboni** [comment]
I don't have important modifications locally, I'm OK too :+1:

**Comment by ylep** [comment]
Okay, I’ll go ahead now

**Comment by ylep** [comment]
I just finished cleaning up PEP8, flake8, and whitespace issues in casa-distro. @brainvisa/release @Hboni  *Please* enable pre-commit now in your working repositories, it will do two things for you:

- automatically clean up whitespace problems (trailing whitespace, empty lines with whitespace)
- notify you of any PEP8/flake8 errors

If you want to commit temporarily non-compliant code (e.g. work-in-progress) you can use `git commit --no-verify` to bypass all pre-commit checks.

However, flake8 and whitespace checks are part of continuous-integration, so any code that does not comply will fail Travis checks.
