### ISSUE TITLE
images download method

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#130]
In casa-distro 2 downloading image files was done using an ad-hoc function in casa-distro.
In casa-distro 3 we are using wget to handle partial downloads and continue former trials.
Thus wget is a dependency. We can pull a singularity image for wget if we don't find it on the host system, but then we have to work using singularity (in vbox/docker modes, we may have to find another solution).
The former download function is still present in casa-distro 3, but unused.
So should we either:
1. adapt other ways of installing wget using docker or virtualbox, and remove the function in casa-distro 3
2. adapt the download function to handle partial downloads, and remove the use of wget

It might be quite easy to adapt 2. and skip a dependency, but maybe wget has some interesting features that makes it a better solution ?

**Comment by sapetnioc** [comment]
I am afraid to encounter some unexpected difficulties in the support of a home made partial download feature. But if it is easy, option 2 is the way to go.

For VirtualBox there is no other download than the complete VM image that will be done with a web browser.
And for Docker we will probably rely on DockerHub to publish images.

**Comment by denisri** [comment]
The modification in the existing download code is very slight actually, but I don't know if we may encounter difficulties as you say... It relies on python urllib so I guess it's mostly OK but I'm not a specialist of file transfer protocols (https etc)
