### ISSUE TITLE
Run-scripts on the host for container programs

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#132]
Up to now the software distribution was built for the exact same systems used in the labs, and installed outside of any container system, and all programs were setup in all users `PATH`.
What will we do for brainvisa 5.0 ? We cannot point a PATH inside a container...
But commands in the PATH used to be run scripts managing paths, environment variables, and running the underlying executable from its "real" location.
Should we re-create these run scripts with container management ?

**Comment by denisri** [comment]
I have written a script in `<casa_distro>/share/scripts/casa_build_host_links` which creates a set of run scripts (bash scripts in `/casa/host/host_bin/` and `.bat` scripts in `/casa/host/win_bin/`) which job is to call casa_distro from the host machine and pass it the command to run. This way the usual commandlines `AimsFileInfo`, `anatomist`,  `brainvisa` can be called normally from the host machine, provided `python` and `singularity` (or `docker`) commands are in the `PATH` of the host machine. We can set this directory in the host machine `PATH`.
For dev environments it's maybe OK. For run environments, the scripts would need to be included in the run image, but should be copied outside of it during the `casa_distro setup` step, because they have to be seen from the host. Or the `casa_build_host_links` script could be invoked at setup time from the container. Some paths should be changed here I guess.

**Warning** I have not tested the windows scripts (I don't have windows) and they are likely to contain bugs currently.

**Comment by denisri** [comment]
Could anyone with a windows machine with singuilarity inside test the singularity **brainvisa-5.0-test2** user image, and try the run scripts in `<env_dir>/host/win_bin/` please ?

**Comment by sapetnioc** [comment]
I am too late on that topic, sorry. But I ask my question anyway : was it not the role of `bv` to launch our software ? We could have imagine a single CEA dedicated `bv`command that would have been installed for everyone.

**Comment by sapetnioc** [comment]
For Windows, I may not understand. There is no Singularity on Windows AFAIK. There is a Linux in Windows with singularity in it. Are the scripts running Linux first or are they just calling Singularity ? In the second case, I am afraid it will not work.

**Comment by denisri** [comment]
There are 2 reasons I see (but that can be discussed of course):
* users in Neurospin/MirCen (or maybe elsewhere also) are used to run commands "directly", and we don't even have a reliable communication channel to tell them the changes (you know people don't read docs...) so they will probably keep using the old commands which either will not work any longer, or will call older versions of the software - this will bring to us extra support work.
* in distributed remote execution (soma-workflow in client/server mode) it is already possible to call commands through singularity or casa-distro, but this needs some non-trivial setup from every user in soma-workflow config files, and this config is likely to need changes each time brainvisa version/location changes. The run scripts allow to handle this transparently without any config.

And anyway it was not a very difficult to provide these scripts, so I thought it was interesting to do it.

For Windows I have probably misunderstood, I thought there was a singularity implementation for windows which was working only when the linux subsystem was installed and enabled. If not OK there is no point in this variant, I will remove them.

Now the whole thing can be discussed, I can remove the scripts, of course, and leave only the command bv (which is still to be written :) ).

**Comment by ylep** [comment]
We discussed this issue today, and agreed on a few things:

- We will put a shared environment (with user-specific home, see #99) somewhere on `/neurospin/brainvisa`
- We will put the `bv` command (#119) and the run scripts of that shared installation in the `PATH` of CEA Linux workstations
- The run scripts will be reimplemented on top of `bv`

**Comment by denisri** [comment]
Summary of the latest discussion:
There are 4 distinct use cases:
* an **admin** installs a brainvisa distro site-wide in a shared environment. The environment will setup mount points etc for the entire site. Install is done using the regular `casa_distro setup` command.
* a **local user** installs a brainvisa distro for himself, in a personal environment. This is done using either `casa_distro setup` or `bv-install` (#144). The host machine needs to have `singularity`, `python` and `casa-distro` installed.
* a **shared user** is using an already installed brainvisa distro on a network (installed by an admin). He doesn't setup a new environment but uses a shared one, and can only customize additional mount points from his personal (home) config. He is using `bv` or run scripts for commands from the installed environment, which can be set in the `PATH`.
* a **developer** installs his own repository and environments using `casa_distro` and possibly `casa-distro_admin`

Thus we must install the `bv` command and libs in each environment (together with run scripts) on the host filesystem (outside of the .sif image) during setup, in order to allow the shared user case especially. This is the job of #145.

**Comment by sapetnioc** [comment]
Here is my detailed view of the use cases. It explain briefly the various steps to install an environment and precise what will be created in which directory. I think that we do not have all the same organization in mind. So let's discuss this until we all agree.

 Admin
-------
An admin installs a shared environment in `<shared_environment>/` directory with `casa_dsitro setup`. Python, Singularity and casa-distro must be installed for each user. For Python, we recommend installation with system packages. For Singularity install with Ubuntu package located in https://brainvisa.info or as explained in Singularity site. For casa_distro, there are two options:
  - Clone source in `<shared_environment>/casa_distro`. If this directory exists, it will always be selected by `bv` command to execute command of this shared environment.
  - Install via `pip` or `setup.py` on each user system

For the Singularity image file, there are two options. If one wants `<shared_environment>/` to be self content, the image can be put in that directory and referenced as a relative file location in `casa_distro.json` (e.g. `../../casa-dev-ubuntu-18.04.sif`). An image shared by several environments should be outside `<shared_environment>/` directory. We may have to adapt `casa_distro setup` options to allow to manage both options.

 local user
------------
A user first read installation page on https;//brainvisa.info to learn how to install what is required. On Windows, it installs WSL2, an Ubuntu distro and a X server. From this point, we assume that user knows how to start the X server and a terminal on Windows. Therefore the rest of the procedure is the same as the Linux one.

Python and pip are installed with system package.
casa_distro is installed with pip.
Installation script is started with `python -m bv.install`. It check available distro and releases available on https://brainvisa.info, present them to the user and allow him to select one. The user system is checked and the script help the user to install Singularity. The selected distro is installed by default in `$HOME/<distro-name>` (for instance `~/brainvisa-5.0`) or in any user chosen directory. The content of this directory is similar as an Admin self content installation.

 shared user
-------------
The user find the bv command and all the scripts to directly run commands inside the container (e.g. `anatomist`, `brainvisa`, `AimsFileInfo`, etc.) in `<shared_directory>/bin` (the directory to put in `PATH`). Except `bv`, each script named `<command>` is simply calling `bv <command> "$@"`.

 developer
-----------
We provide a recommended organization for developers. Python is installed with system package. Singularity is installed with Ubuntu package located in https://brainvisa.info or as explained in Singularity site. Casa-distro git repository is cloned in `~/casa_distro/src`. `casa_distro` and `casa_distro_admin` are explicitly pointing to that directory (via `alias` or `PATH`). Development environments are created with `casa_distro setup_dev`.

**Comment by sapetnioc** [comment]
After a discussion with @denisri , we think that it can be interesting in Singularity user and developer use cases to use casa-distro version embedded in image instead of installing a version with pip. This way, we are sure to have a version coherence. In both cases, users would only have to install Python/Singularity and to download a singularity image (either a dev or user image). Then,  to install a casa_distro environment in `<environment_directory>` the whole setup would be done from the container by running something like : 
```
singularity run <image_file> -B <installation_directory>:/casa/setup setup
```
According to the image type, it would install a user or dev environment.

**Comment by sapetnioc** [comment]
This issue is obsolete. It contains interesting discussion about user workflows that I will update an put in a new issue.

**Comment by ylep** [comment]
Re-opening because the run-scripts are not created with the new workflow (using `bin/bv bv_maker`).

**Comment by denisri** [comment]
I have added the run-scripts creation at the end of `bv_maker build` (brainvisa/brainvisa-cmake@69ae9ddd3bbb3945b2efe05b6673d05907d8af39) but using my older script (share/casa-distro/scripts/cassa_build_host_links), whereas @sapetnioc has written a newer way to build the scripts somewhere but it's inside the setup process. We have to update this and have only one implementation for it.

**Comment by sapetnioc** [comment]
There is no more need to make a script. Just a symlink to `bv` is enough. The name of the symlink is the command that bv will start.

**Comment by denisri** [comment]
Normally yes a symlink is enough, and that's what my script does. Except when the filesystem doesn't support symlinks (windows, some external devices... - the script takes care of that) and we still have to provide the list of executables that should be symlinked there, and the way to "install" the bv script and a few others which are handled differently. So the `casa_build_host_links` script, or its replacement in one of your functions, still deserves existing, but we have to merge them.

**Comment by sapetnioc** [comment]
For info : to date Singularity only works on Linux. Therefore, even under Windows 10 we always use a file system that supports symlinks (via WSL2 or VirutalBox).

**Comment by denisri** [comment]
For now yes (and on Mac a little bit). However users might install the brainvisa distribution on a windows filesystem (a USB key that you can easily plug into any machine, for instance...) which doesn't support symlinks. Maybe it's not a critical issue, but as at first we were not using symlinks, I kept the code in my script in case symlinks are not working.
And maybe we will add back support for docker, or singularity will work on windows...
