### ISSUE TITLE
Choose base system for VirtualBox

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#133]
We must choose the distro to use for our VirtualBox images. I tried ubuntu and xubuntu (18.04). Xubuntu is supposed to be more lightweight but it has an important drawback for users : the screen is not automatically resized when the VirtualBox window is resized. Moreover, resizing windows in xubuntu desktop was painful  because the active zone is one or two pixels wide and I was not able to resize both horizontally and vertically by moving the corner.

I do agree that is would be good to choose a lighter distro than basic Ubuntu but it is necessary to test the ergonomics of the system in VirtualBox. Any distro proposal ?

**Comment by sapetnioc** [comment]
I am trying [Lubuntu](https://lubuntu.me)

**Comment by sapetnioc** [comment]
lubuntu seems ok. But we could still remove a lot of packages.

**Comment by ylep** [comment]
If the default settings of Xubuntu are a pain to work with, then let's forget about it. I mentioned not-so-good memories of working under LXDE (on which Lubuntu is based), but it probably has improved since then.

**Comment by sapetnioc** [comment]
To date lubuntu has been choosens a base system for VirutalBox. I will create a new issue to test and improve the VM. Any system change will be discussed in that issue.

**Comment by sapetnioc** [comment]
See #141
