### ISSUE TITLE
Consider OVF format for VirtualBox release

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#136]
Currently casa-distro is using the internal VirtualBox disk format (VDI) to publish VM. But exporting a full VM (not only the disk) in OVF format reduce the size by two for casa-run image (4.54 GiB v.s. 10.76 GiB). Moreover, it is easier for user to import a full VM in VirtualBox. I see only two drawbacks:

- There are two files to publish instead of one (one very small and a compressed disk image)
- The disk has to be imported, this requires to have more space available during importation (the downloaded disk can be deleted after)

**Comment by denisri** [comment]
I don't know the formats - is OVF a format external to Virtualbox ?
Anyway it seems reasonable to use a compressed image and reduce the amount of download.

**Comment by sapetnioc** [comment]
`VBoxManage export` supports three formats : OVF, OVA and tar.gz. AFAIK, OVF and OVA are supposed to be independant of VirtualBox. AFAIK, OVA is just a single file version of OVF. Therefore, I am making an OVA export and will try its usage on Linux and Windows.

**Comment by sapetnioc** [comment]
In OVA format, we can add the following meta information  :
- product
- product URL
- vendor
- vendor URL
- version
- description
- eula
- eulafile

Do we want to be able to define some of these fields with casa-distro ? For instance by adding some optional parameters to `casa_distro_admin create_user_image` ?

**Comment by denisri** [comment]
We could at least set (automatically) product, product URL, and version.

**Comment by sapetnioc** [comment]
Now all VirtualBox images are created in *.ova format (AFAIK, OVF format is in two files, OVA is the same with only one file). I published a test image as well as corresponding system and run images. I also uploaded a dev image but we did not plan yet to develop with VirtualBox.
