### ISSUE TITLE
add python-modernize, flake8 and autopep8 to images

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#14]
casa-distro dev images should include autopep8, flake8 and python-modernize software

**Comment by ylep** [comment]
`pre-commit` can be configured to enable itself automatically on newly cloned repositories: see https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories

**Comment by denisri** [comment]
done in #15.
Images are rebuilding.

**Comment by ylep** [comment]
I will add the call to enable `pre-commit` in `bv_maker` instead of the `casa-distro` images, so it will ensure that the pre-commit checks are used by as many people as possible (existing repositories, people building outside of casa-distro).

So from my point of view we can close this issue now.

**Comment by denisri** [comment]
images have been pushed.
