### ISSUE TITLE
writable images fail to be created on ubuntu 16.04

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#146]
OK my system is old...
The overlay creation issues a command:
```
mkfs.ext3 -d /tmp/something /home/someone/casa_distro/something/overlay.img
```
but on this system the command doesn't have the `-d` option.

After that casa-distro is unable to use any previously setup environment: it tries to read this overlay even when it's not selected, and fails with an error.

Then I don't understand the way this `-d` option is used: it seems to copy a temp directory just created, and apparently still empty...
I could remove the workflow, use an existing one based on ubuntu-18.04 and create the filesystem from here, containing /upper and /work directories (expected by singularity), but I had to have a working image first.
Otherwise we would need to create the empty filesystem (without the `-d` option), mount it as root and create there the directories...

**Comment by sapetnioc** [comment]
AFAIK, the trick of the empty directory just created is used to set the appropriate user rights of the new file system root.

**Comment by denisri** [comment]
When I do it manually, singularity complains that there are no directories "upper" and "work" here, but maybe assigning user rights allows it to create them, so maybe I understand.

**Comment by denisri** [comment]
It's strange: I can create the filesystem using the exact same command `mkfs.ext3 -d /tmp/something...` from an ubuntu 18 container, but then I get the same error from singularity for the `upper` and `work` directories. If I create the directories inside `/tmp/something/` before calling `mkfs.ext3`, then it works correctly (without sudo permissions).
Anyway we have a kind of solution.
