### ISSUE TITLE
/casa/host/install paths take priority over dev files

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#150]
In a developer environment, the developer normally gets his build directory (`/casa/build`) in the `PATHs` in order to run / test the programs he develops.
But once an install has been performed (`make install-runtime`, or using `casa_distro_admin create_user_image`), and the container is restarted, `PATHs` then automatially point to `/casa/host/install`, without a notice.
Later modifs in codes are thus ignored, which is unexpected for the developer.
Switching to `/casa/host/install` paths should be manual I guess (the simplest is to let the user call `/casa/host/install/bin/bv_env.sh` when he wishes)
Do you agree / disagree ?

**Comment by denisri** [comment]
See for instance brainvisa/anatomist-free#20 which might result from this problem.

**Comment by sapetnioc** [comment]
Yes I think we can remove the /casa/install directory from the path in dev
environments. This environment is activated in user environments (full
images with /casa/install inside) by sourcing /casa/install/bin/bv_env.sh
in image entry point.

**Comment by denisri** [comment]
Moreover it's not the same path: `/casa/install` for user images, `/casa/host/install` for dev images with install.
