### ISSUE TITLE
environments naming is ambiguous

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#155]
The branch does not appear in the environment name in a dev environment, and no question is asked before overwriting, thus:
```
casa_distro setup_dev distro=opensource branch=master
casa_distro setup_dev distro=opensource branch=latest_release
```
ends up with a single environment, `opensource-dev-ubuntu-18.04` configured with branch `latest_release`. The former one with branch `master` has been erased (modified and overwritten, actually).
It this really what we want ?
We could ask the same question for other environment identifier variables which do not appear in the environment name (`container_type`, maybe `image`).

**Comment by denisri** [comment]
I mean, we can of course force a new environment by specifying a new `name`, different from existing ones. But is it OK when `casa_distro` erases / modifies an existing environment without asking confirmation ?

**Comment by ylep** [comment]
1. I think that `casa_distro setup` and `casa_distro setup_dev` should just refuse to create an environment if a directory of that `name` already exists. If we ever want to support modifying an environment, that should be done through `casa_distro update`.
2. For the naming of environments, I think that we should use the actual branch name that is used by `bv_maker`. Having `dev` synonymous with `master` is not very explicit, and it is still time to change it. Therefore we would have `brainvisa-master-ubuntu-18.04` and `brainvisa-latest_release-ubuntu-18.04` Do you agree @sapetnioc?

**Comment by sapetnioc** [comment]
Yes. `-dev` was used as opposed to `-run` but the latter has disappeared and the way we organize environments has changed.

**Comment by denisri** [comment]
OK.
