### ISSUE TITLE
Stop using fake container_options for OpenGL

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#159]
We are currently using the `container_options` variable of `casa_distro.json` to store options related to the OpenGL strategy:

- `--nv`
- `--no-nv` (fake option)
- `--softgl` (fake option)

In my opinion this is not a good strategy, because when we have an environment that is shared between users, they might have different hardware and thus need different OpenGL options.

If we need to store an OpenGL strategy for a given environment (do we?) I propose that we add an `opengl` option to `casa_distro.json`, which can take the same values as the command-line option (`auto`, `container`, or `software`). The command-line value should still override the value stored in `casa_distro.json`. By default we would set that value to `auto`.

This mechanism could also be made more general, allowing to store defaults for all command-line options in `casa_distro.json`.

@denisri @sapetnioc Do you agree with this change?

**Comment by denisri** [comment]
I quite agree ;)
I did this myself while making myself the same remark, but as it was easier to do, you know....

**Comment by denisri** [comment]
Is this ticket still up-to-date ? --no-nv and --softgl options seem not to be still in the code (in 3.0 branch), are they ?

**Comment by ylep** [comment]
Right, this was fixed in 3743dda73ed12def850252c69bfa25d621d4bf21
