### ISSUE TITLE
Issue with netcdf install (again)

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#16]
The netcdf problem has reappeared on the latest Ubuntu 16.04 image that @sapetnioc has rebuilt. [[Jenkins build log]](http://brainvisa.info/brainvisa_builds/view/3%20-%20build/job/brainvisa-bug_fix-ubuntu-16.04-all-build-is234198/lastFailedBuild/)

```
make[2]: *** No rule to make target '/usr/local/lib/libnetcdf.so', needed by 'lib/libaimsminc.so.4.6.2'.  Stop.
CMakeFiles/Makefile2:38494: recipe for target 'build_files/aims-free/aimsdata/src/aimsminc/CMakeFiles/aimsminc.dir/all' failed
make[1]: *** [build_files/aims-free/aimsdata/src/aimsminc/CMakeFiles/aimsminc.dir/all] Error 2
```

There is a weird symbolic link named `*.so*` in `/usr/local/lib` pointing to libnetcdf…

**Comment by denisri** [comment]
I'm rebuilding images and I do have libnetcdf in /usr/local. I'll publish them again.
