### ISSUE TITLE
Implement a robust heuristic for opengl=auto

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#160]
We need to find a good heuristic for `opengl=auto` to choose a working OpenGL implementation depending on available hardware, X server configuration, etc.

As a reminder, we currently support three OpenGL implementations:

- the GL libraries of the NVidia proprietary driver (activated with `singularity --nv`) give best performance on NVidia hardware, but are not always safe to use:
  - when `nvidia-container-cli` is not installed, programs linked with OpenGL may cause random segfaults #153
  - when `nvidia-container-cli` is not installed, and the current X server is unable to use the NVidia hardware (such as when using `x2go` or `Xvnc`) programs linked with OpenGL will consistently segfault

- the DRI-enabled mesa libraries installed in the container through APT packages (used if neither `--nv` nor `SOFTWARE_OPENGL` are used) allow using hardware acceleration on non-NVidia hardware (e.g. Intel chipset), but they fail if the X server has access to NVidia hardware (#101)

- a set of mesa libraries compiled for software rendering only, that we install under `/usr/local/lib/mesa` in the images (see #101) for use when everything else fails. It is activated by setting the `SOFTWARE_OPENGL` environment variable to `1`, which causes the `entrypoint` script to set `LD_LIBRARY_PATH` accordingly.

Additionally, we want to pass `--nv` to Singularity even in non-GUI mode in order to support CUDA in the container when running over SSH (via soma-workflow or otherwise).

**Comment by denisri** [comment]
What's the state of this issue ?
Is it solved by #153, #101 and #59, or is there still something to do on this topic ?

**Comment by ylep** [comment]
I would say that this needs more testing, to confirm that the new heuristic works in all real-world settings that we want to support. We could keep this issue open as a reminder, or close it and reopen it when we find a bug in the heuristic.

**Comment by denisri** [comment]
OK let's keep it open and see if we still run into problems in the next weeks.
