### ISSUE TITLE
Add a bbi_daily command to casa_distro_admin

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#161]
In [BrainVISA Build Infrastructure (BBI)](https://bioproj.extra.cea.fr/redmine/projects/catidev/wiki/Brainvia_build_infrastructure), there will be some machines that will be targeted to do some builds and tests. This command would be used to perform these tasks and would be typically used in a crontab on each machine. It would do the following things (and would log progress and result in Jenkins server) :
- Update casa_distro to latest master version and restart for the next steps
- Parse all configured environments selected with a filter as with `mrun` command
- Update dev and run images used by selected environments (from https://brainvisa.info)
- For all dev environment, perform the following tasks :
  - `bv_maker sources` 
  - `bv_maker configure`
  - `bv_maker build`
  - `bv_maker doc`
  - perform all tests (as `bv_maker test`)
- For all user environment
  - find the corresponding dev environment
  - recreate the user environment image with `casa_distro_admin create_user_image`
  - perform all tests defined in the correponding dev environment but execute them in the user environment

**Comment by denisri** [comment]
I'm mostly OK with that.
1. How would you link a user environment and a dev environment ? I mean, not all user envs are going to run tests, some stable, already released ones are already tested and don't need to be tested / rebuilt again: this is more a "release-candidate feature".
2. Do we need to write a new command for that, or modify `casa_distro` ? I mean most/all of the steps are a run of casa_distro. The update step could be a `casa_distro auto_update` (where / how is it installed and updated is still to be defined: pip ? git ? inside one container environment ?). The missing part then would be to chain several `casa_distro` commands - we could imagine doing it in a similar way as `bv_maker` (`casa_distro auto_update pull_image bv_maker etc.`), but the arguments parsing is more complex and even completely ambiguous (a `run` command has a commandline with arguments which we don't know where they stop). But I like the idea of running everything in a single command like what we used to do using `bv_maker` (run the command, then go have a coffee).

**Comment by sapetnioc** [comment]
This command could be a script out of casa_distro. It is really dedicated to "official" BrainVISA Build Infrastructure, it supposed to be run in a BrainVISA Build Environment (BBE) wich is a specific account (a-sas-ns-brainvisa or brainvisa on brainvisa.info) with a specific `base_directory` containing only "official environments" that we can update, test and publish. It may be used by developers on their environment but it is not the goal. If they have many environments it can be tricky.

To my opinion,  the user environment tests are more a replacement of the package test than release_candidate. But when we make a release, we will probably add a dev environment for the release_candidate branch and create the corresponding user environments for various distro.

In this specific environments list, it is supposed to exist only one dev environment for a given distro, branch and system. This is how I plan to make the link from a user environment. If several are found, it will be an error.

There is a need for a new command for several reasons : 
- Its behavior is dedicated to BBE, it may no be adapted to any admin environment
- It may use some specific default value for BBI (for instance `base_directroy`)
- It will log results in BrainVISA Jenkins server by default. Jenkins code may be removed from `bv_maker`, I did not think too much about that point yet.

**Comment by sapetnioc** [comment]
I forgot to say that I proposed in [BrainVISA Build Infrastructure (BBI)](https://bioproj.extra.cea.fr/redmine/projects/catidev/wiki/Brainvia_build_infrastructure) that in a BBE, casa_distro (and casa_distro_admin) is an alias to the command in sources located in `~/casa_distro/src`. Therefore, updating the source is just performing a `git -C ~/casa_distro/src pull`.

**Comment by sapetnioc** [comment]
Some commands required by tests, such as `vip_test_well_composed_configurations`, are not installed by `make install-runtime` and `make install-doc`. Therefore [some tests fail in user environment](https://work.cointepas.net/jenkins/job/brainvisa-5.0-rc/1/). Is there a specific target to install for these commands ?

**Comment by sapetnioc** [comment]
For my last comment, `make install-test` is what I was looking for.
