### ISSUE TITLE
Make every environement directory idependant

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#175]
I am working in branch `setup_with_singularity` on the possibility to install an environment from scratch using an Singularity and the downloaded image (either user or dev). On this process it appeared that if a casa-distro instance is shared by several environments, it is difficult to ensure the compatibility with all the environments. Therefore I started to work with the idea to make eachenvironments being a self-content directory. But it has consequences to discuss on the way we use casa-distro :
- No more central repository directory (`~/casa_distro`). Images and environments can be installed anywhere.
- Scripts to directly call commands from host would be installed in `<environment_dir>/bin`. We would need a way to update these scripts when some are created or deleted in a developer environment.
- Some commands assuming a global directory would disappear : `list`, `list_images`, `mrun`, `clean_images`.

**Comment by sapetnioc** [comment]
This method is already working for user images generated from `setup_with_singularity` branch. I was able to do :
```
mkdir /tmp/test
singularity run-B /tmp/test:/casa/setup  ~/casa-distro/brainvisa-test-20201127.sif setup
/tmp/test/bin/anatomist
```

**Comment by sapetnioc** [comment]
I am now trying to do the same to create a dev environment from scratch :
```
mkdir /tmp/dev
singularity run -B /tmp/dev:/casa/setup ~/casa-distro/casa-dev-ubuntu-18.04.sif setup brainvisa master
/tmp/dev/bin/bv_maker
```

**Comment by denisri** [comment]
I agree except for the last point

> Some commands assuming a global directory would disappear : `list`, `list_images`, `mrun`, `clean_images`.

* I don't understand if you mean that images (especially dev images) will not be shared any longer between environments. As images are large (several GB), sharing them seems important.
* These commands were very handy, and as a developer I often navigate between several dev environments. I'm a bit disapointed about dropping this easy way to handle them conveniently.

Would it be possible to imagine that casa_distro has a "common part", which would not evolve in a non-compatible way too often (OK this assumption is very vague), and which would handle the inter-environment part, with the commands `list`, `list_image` etc., and which would call externally environment-specific commands ? I mean, `run` and `mrun` would not do it directly as they do today, but instead would determine the environment directory, then call `bv` in there. The common part would be lightweight (thus would not suffer heavily from possible incompatibilities between environments), and would delegate environment-specific things to each of them. Once at least an environment is installed, the user/developer could pick any of them (set it in his `PATH`) to use the common part.

Minor point:

> Scripts to directly call commands from host would be installed in `<environment_dir>/bin`

Scripts would be installed from within the container, thus need to be installed in a directory visible (mounted) by the container and still on the host filesystem. This was the meaning of `<environment_dir>/host`, was it not ? If we are now using `<environment_dir>/bin` etc which should thus be visible from the container, why keeping the `host` subdirectory ?

**Comment by sapetnioc** [comment]
* Yes images will be shared, we cannot afford to duplicate them. When you start a container, you get a `SINGULARITY_CONTAINER` env var containing the image file name on the host file system. It allows to setup the environment with a reference to the image (however if the image is moved, `casa_distro.json` must be modified). Therefore, if you setup several environments with the same image, they will all reference the same image file.

* I think it will be fairly easy to get back the functionalities that are removed from casa-distro. If I want to remove them it is because it is not really compatible with the new installation and setup system. But there may be a way to keep them by mounting the `~/casa_distro` directory when creating a dev environment from scratch. This would allow to have the same setup mechanism but with the possibility to manage several environments. I will investigate that option. Then we will discuss to decide if we support multiple environments in casa-distro or next to casa-distro.
 
* The setup command of the container image is a special one that required that the whole environment directory is mounted in `/casa/setup`. This allows to create scripts in `bin`. It works well for user images since all commands are known during setup (they are in `/casa/install/bin` in the container). But for developer environment commands are only available after a build, therefore there is something to think about here (for instance always mount `<environment_dir>/bin` and modify `bv_maker` to update these scripts). Note that the scripts are rather simple, here is the one for `anatomist` :
```
#!/bin/sh
bv="$(dirname -- $0)/bv"
"$bv" anatomist "$@" 
```
We probably can use a unique script by replacing `anatomist` by `$(basename -- $0)`.

**Comment by sapetnioc** [comment]
I confirm that putting this script in `bin` directory:
```
#!/bin/sh
bv="$(dirname -- $0)/bv"
"$bv" "$(basename -- $0)" "$@"
```
Allow to create an `anatomist` command with a simple symlink on this script

**Comment by denisri** [comment]
If `anatomist` is not another symlink (say for instance in `$HOME/bin/` pointing to `<environment>/bin/anatomist` without `bv` next to it. But this situation is rather improbable.

**Comment by denisri** [comment]
With a little modification to `bv` itself, the "unique script where all commands could point to" could perhaps be `bv` itself, can't it ? When invoked with `argv[0]` not being `bv`, it could react as your script ?
The fact that run scripts are not bash scripts any longer but a python `bv` command should not really matter, does it ?

**Comment by denisri** [comment]
I'm doing that :)

**Comment by sapetnioc** [comment]
I have modifications pending on `bv` on my branch. Where are you going to do the modifications ?

**Comment by sapetnioc** [comment]
In fact I have many things not pushed. If you want to test the `setup_with_singularity` branch, I must update it first.

**Comment by denisri** [comment]
It's pushed on 3.0 as it is rather independent from what you are doing. It will not cause much trouble to merge (and I can do so if needed).

**Comment by sapetnioc** [comment]
No,, it'ok. That was just to know.

**Comment by sapetnioc** [comment]
Finally, there is no harm keeping multiple environment commands such as `list` and `mrun`. The remaining question is : how far we go in the documentation and support of multiple developers environments ? For independent environments, users and developers are taken by the hand to setup and use their environments. For the central management of several developement environments, one must follow some rules to organize its environment directories, choose which casa-distro to use and make the corresponding shortcuts in its shell environment (e.g. PATH or alias).

**Comment by sapetnioc** [comment]
I think this is done. We are in a debug/small improvement phase now.
