### ISSUE TITLE
Remove host directory from environments

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#179]
There is no more reason not to mount the whole environment directory in the container. This will allow container commands to modify host specific commands (for instance shortcuts to commands in `bin` directory). This can be done by removing the `host` directory from environment directories and making casa-distro mount the whole environment directory in `/casa/host` (there are other image directories in `/casa` such as `brainvisa-cmake` or `casa-distro`).

I propose to make this change in a non backward compatible way with existing 3.0 environments. Users would have to manualy remove `host` directory in each environment.

**Comment by denisri** [comment]
I agree.
