### ISSUE TITLE
The DEB package name ('singularity') conflicts with another package, should be renamed 'singularity-container'

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#184]
On Debian the `singularity` package name refers to [a video game](https://packages.debian.org/buster/singularity). The container engine that we use is traditionally named `singularity-container` (at least [on NeuroDebian](https://neuro.debian.net/pkgs/singularity-container.html)).

We should really rename our package to `singularity-container` so that it will replace the one from NeuroDebian. Otherwise we may end up in a situation where both are installed, but they will inevitably conflict with each other.

**Comment by sapetnioc** [comment]
I may miss some knowledge to fix that myself. I just adapted the procedure given by @nsouedet to Singularity. Where is the package name given ? If it is only in the filename this is easy to fix. If the name in somewhere inside the package, I do not know where it is defined. The script creating a RPM that is converted to a DEB is here : https://github.com/brainvisa/casa-distro/blob/3c61c13a171e581cefe38290661e7f5aba4996be/python/casa_distro/admin_commands.py#L110

**Comment by denisri** [comment]
I think I found a way by replacing things in the `singularity.spec` file.
