### ISSUE TITLE
Using 'bin/bv bv_maker' sets the OpenGL libs on LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#187]
With the new scheme where casa-distro is extracted from the images, I understand that `bv` should be used instead of `casa_distro run` or `casa_distro bv_maker`.

The problem is that now we have to pass `opengl=container` explicitly to avoid having the OpenGL libraries on LD_LIBRARY_PATH:

```shell
bin/bv opengl=container bv_maker
```

If we forget to do it (`bin/bv bv_maker`), we get an error during the `configure` step (which is the safeguard I added to fix https://github.com/brainvisa/brainvisa-cmake/issues/63).

Here are some suggestions to fix/mitigate this issue, what do you think @sapetnioc?

1. Add a different entry point for developers (maybe `bin/bv-dev`?) which never mounts opengl libraries (equivalent to `opengl=container`). That command would become the preferred way of opening a developer shell in the container, or running any compilation work.
2. Add a special wrapper script for `bv_maker` (`bin/bv_maker`) at the same time that we add `bin/bv`, which runs singularity with the appropriate options.

**Comment by sapetnioc** [comment]
I would be in favor of a third option : make `bv bv_maker` call `casa_distro bv_maker` and let casa-distro set appropriate default values. It may seem a bit weird but for me the most important thing is to make our framework usage easy to understand for users (including developers). But it will be difficult to explain why `bv bv_maker` can be run but lead to an error but `bv-dev bv_maker` or `bv_maker` is ok. I like the idea that any user can remember and use a single entry point : `bv`.

**Comment by ylep** [comment]
I agree with your reasoning, but on the other hand this will keep developers ignorant of the problem, so I fear that at some point one will attempt to run `bv_maker`, or worse, `make` (where there is no safeguard), in a shell inside of a container, where it can result in a broken build which is difficult to debug.

Thefore, I would argue that we should implement both your suggestion (special-case for `bv bv_maker`) and my first one (`bv-dev`), and encourage developers to use `bv-dev` for all compilation-related work.

**Comment by denisri** [comment]
I'm coming back on this problem which has been left aside for a rather long time.
The solutions you propose would allow to compile the programs successfully, but none of them is really transparent and convenient. Different ways of working are used by different developers: for instance I personally often use a shell in the container to run programs, and I would appreciate to be able to build from it, and right now I cannot, and no doubt other developers will try so and and up with broken builds.
We could perhaps modify bv_maker, rather from its `bv_maker.cfg`, to modify `LD_LIBRARY_PATH` internally during its run, but this would not affect `make` commands run directly from the shell, and I see no way to do that in `make`. Is it possible at all ?

(By the way we have no `bv shell` command. We can do that using simply a `bv bash` command but it somewhat differs from the `casa_distro shell` we got accustomed with - this is not important, of course)

**Comment by sapetnioc** [comment]
To make it simple to explain for users, can we say that a developer Singularity environment has two execution modes (`gui=yes` and `gui=no`) and that `gui=yes` must never be used for compilation ?

If yes, what do you think of setting `gui=no` by default for all commands (including `run`) for dev environments ?

To limit the possibilities of running a build command in a gui enabled environment, we could modify casa_distro to add, in the case of a dev environment with `gui=yes`, a special directory in the beginning of `PATH` that would contain the commands we want to disable (`bv_maker`, `make`, etc.). These commands would simply fail with an explaination error message.

**Comment by ylep** [comment]
> We could perhaps modify bv_maker, rather from its `bv_maker.cfg`, to modify `LD_LIBRARY_PATH` internally during its run, but this would not affect `make` commands run directly from the shell, and I see no way to do that in `make`. Is it possible at all ?

For that reason, I have modified `bv_maker` to display an error message instead of silently removing `/.singularity.d/libs` from `LD_LIBRARY_PATH` (https://github.com/brainvisa/brainvisa-cmake/pull/68).

We currently have two safeguards: one in `bv_maker`, and one in `cmake`. Adding one to `make` would be tricky and ugly... but then, we can hopefully rely on proper specification of the dependencies in `cmake` to keep the linker from messing things up (like the fix you did in https://github.com/brainvisa/anatomist-free/commit/187d854b15f9b9c21eccf278d55a8f87bfcee3d2).

**Comment by ylep** [comment]
> can we say that a developer Singularity environment has two execution modes (`gui=yes` and `gui=no`) and that `gui=yes` must never be used for compilation ?

This is not sufficient since the changes I did in https://github.com/brainvisa/casa-distro/commit/3743dda73ed12def850252c69bfa25d621d4bf21: the nvidia libs are now used regardless of `gui`, because they are necessary for GPU-acceleratation in commandline scenarios, and they are also necessary to prevent a segfault of graphical programs in some setups (see https://github.com/brainvisa/casa-distro/issues/160 and https://github.com/brainvisa/casa-distro/issues/101 for the gory details). The correct option to pass is `opengl=countainer`, which I agree is really not a good name in that context.


> a special directory in the beginning of `PATH` that would contain the commands we want to disable (`bv_maker`, `make`, etc.). These commands would simply fail with an explaination error message.

I like this idea, but since we already have safeguards in `bv_maker` and `cmake`, we should only need it for `make`. I suggest that we make the implementation even simpler by defining a shell alias or shell function for `make` in `.bashrc`, which does the checking without needing to add any logic to `casa-distro` itself. I propose to add it as part of https://github.com/brainvisa/casa-distro/issues/173.

**Comment by denisri** [comment]
I'm not sure (I don't remember, actually) if brainvisa/anatomist-free@187d854 is enough to have things build correctly using `make` (once the configuration has been done) or not, we should give it a second try. If yes, then changing the `LD_LIBRARY_PATH` within bv_maker during config time (possibly based on a config option) would completely solve the problem, without the need of user-visible commands or options. For me it would be the best option, not needed specific shells, but it needs some testing.

**Comment by denisri** [comment]
In the original description of this problem (#113) it was not completely clear but it seemed to happen only on Ubuntu 16.04 hosts, because of the different implementation of libGL on Ubuntu 16/18. Does it happen on Ubuntu >= 18.04 ? I don't remember I ran into it on Ubuntu 18.04 hosts. Now if I use `bv bash` or `casa_distro shell` (with gui active) I cannot build any longer due to the safeguard in bv_maker, whereas maybe it would work. It's a bit a pity to be forced to open another container without GUI when it's not necessary (especially when using an overlay which forbids to open several containers), so we may want to be more specific on the safeguard. But I still don't understand, and cannot reproduce the situation when the problem occurs. Can anybody describe how to reproduce the problem, and does it still exist after brainvisa/anatomist-free@187d854 ?

**Comment by ylep** [comment]
I think that we can consider this issue fixed since https://github.com/brainvisa/casa-distro/commit/e0d62e3f1c18f47f06bdf00408c7f8e24cf43f02
