### ISSUE TITLE
do we set main projects versions to 5.0.0 ?

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#189]
Do we set main projects versions (soma-base, aims, anatomist) to 5.0.0 for the new release "brainvisa 5.0", or do we leave them to 4.7 ?

**Comment by ylep** [comment]
Summary of our discussion: yes, we set the version of all brainvisa-specific projects to the version of the release.

Exceptions are the populse projects (capsul, populse_db, soma-workflow) because they may be distributed outside of the BrainVISA releases.

**Comment by denisri** [comment]
Does it apply to development tools (brainvisa-cmake, casa-distro) ? I guess not but what's your opinion ?

**Comment by ylep** [comment]
I’d say that version numbers do not really matter for these tools...

However, considering that these will only ever be used in the context of BrainVISA distributions, I think it doesn’t hurt to synchronize their version numbers as well?

**Comment by sapetnioc** [comment]
I would say no for casa-distro just because we already talked about the v3 for weeks. Not changing that mean less things to explain to people. But it is not a big deal if we decide to align as many versions as possible.

This is a typical Normand answer

**Comment by denisri** [comment]
Well let's not change them then :)

**Comment by denisri** [comment]
OK then it's done.
