### ISSUE TITLE
Remove singularity from the casa-dev images?

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#192]
If I understand correctly we have abandoned the idea of running singularity inside of singularity for testing the generated images, in favour of managing tests with the `bbi_daily` infrastructure.

As a result, we can remove singularity from the casa-dev images, do you agree @nsouedet @sapetnioc @denisri ?

**Comment by sapetnioc** [comment]
Yes, I do not see a real use case for using singularity in singularity.

**Comment by denisri** [comment]
I guess yes (but I haven't looked at the test bbi yet...)
