### ISSUE TITLE
User images installed with /casa/setup lack some configuration keys

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#201]
When a user image is installed using `singularity --bind <path>:/casa/setup <image>.sif`, the `casa_distro.json` that is created is missing important keys: it has `"distro": "unkown_distro"` (sic), and the `"version"` key is missing completely. This is causing `bbi_daily` to fail.

@sapetnioc The question is, where in the image is this information supposed to be stored? Now `setup_user` is looking for the `CASA_DISTRO` environment variable, which does not exist, hence `unkown_distro`. It is not even looking for `version` in any environment variable.

Should we write these environment variables in some shell script that is sourced by `entrypoint`, so that they are available at the time of `setup_user`?

**Comment by denisri** [comment]
I guess this information should be taken from the user image itself, since it contains a specific distro/version in it.

**Comment by sapetnioc** [comment]
Yes, information must be in the image. CASA_DISTRO is supposed to be stored in the run image env vars (I chose that because it was already there) but obviously its missing. I will check image creation. The version can only be set at user image creation time but it is also supposed to go into the image. I do not understand what happened, `bbi_daily` used to work.

**Comment by ylep** [comment]
Since d472ac8322f1396d227052ff70d81dc2869274dc the `CASA_DISTRO` variable is set correctly in the images, but `version` is still not handled. Do we even need it? It seems that its only purpose so far is to be written to the JSON metadata of the user images, but it is not used for any other purpose.

We could solve that issue by:
- either, getting rid of `version` by making it an *optional* parameter to `create_user_image`,
- or, writing it into the user images in a `CASA_VERSION` environment variable, and extract in in `setup_user` in order to write it in `conf/casa_distro.json`.

@sapetnioc which way do you prefer?

**Comment by sapetnioc** [comment]
I think version is important, in the future, to say if a user directory simply called `~/brainvisa` was installed with branvisa-5.0 or brainvisa-5.1 (or any other version).
