### ISSUE TITLE
casa-distro should not be installed in the container (/casa/host/build or /casa/install)

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#209]
I can see no good use-case for having the casa-distro binaries in `/casa/build/bin` or `/casa/install/bin`. I think that their presence can only create confusion for users.

I guess that this can be done by changing `build_model` in `components_definition.py`?

However, we have to change our way of calling `configuration_gui` if we stop installing casa-distro in the build directory.

**Comment by ylep** [comment]
In order to clarify the parts of casa-distro that should be used from the host, and from the container, I propose to do the following (to be discussed during our visio this afternoon): 

- change the `build_model` of casa-distro to use a `CMakeLists.txt` that installs nothing (except Sphinx documentation)
- move `configuration_gui.py` out of the `python/casa_distro` directory, because it is designed to run in the container (maybe put it in a `containerbin` directory in the `casa-distro` repository?)
- also move the `setup_user` and `setup_dev` commands from `user_commands.py` into a command in the `containerbin` directory
- change `bv` to run `configuration_gui.py` from the casa-distro source directory (either `/casa/host/src/development/casa-distro/master`, or fall back to `/casa/casa-distro` for user images)

**Comment by denisri** [comment]
If we change the build model and don't install programs, then a custom "host" installation of casa-distro (from github sources) will not install them on a host either. This is a bit weird... Your point is OK in the case of a container install...

**Comment by ylep** [comment]
Do we want to keep supporting a "host" installation? There a 3 ways that we could do this:

- support using casa-distro from its sources (this works already and we should continue to support it)
- install as part of a BrainVISA build tree on the host (currently supported thanks to the `pure_python` build model, but I see little point in continuing this because we are moving away from having BrainVISA build trees on the host)
- through `setup.py` / `pip install` (I think we do not need this, because users should use the “container-driven” installation)

Besides, there is the “container-driven” installation mechanism (`singularity run -B ...:/casa/setup`) which I think should be the main entry point for users.

**Comment by denisri** [comment]
> change bv to run configuration_gui.py from the casa-distro source directory (either /casa/host/src/development/casa-distro/master, or fall back to /casa/casa-distro for user images)

I'm working on it, but it's not so easy to call `python -m something` in a container and set a custom pythonpath that we don't even know where it is from outside the container. So my current implementation is to call `bv` inside the container, and `bv` detects if it is inside a container or not, and adapts the `PYTHONPATH` if needed. In this context, `bv`could be called from outside or within a container, and react transparently. It is a contradiction to what I said before in #210 about clearly separating things that should run inside or outside a container. Either `bv`is a "clearly identified exception" to that, or I write another command just to run the GUI, which would perform detection of the installation paths.

**Comment by denisri** [comment]
> move bv away from the bin directory (maybe into a share/hostbin directory) because it does not work from the casa-distro sources, only when installed by setup_user

`bv` does work from the sources. Does it not ? For me it does... It should since in a dev environment, `bv_maker build` makes a symlink to the sources in `/casa/host/bin/`, which allows it to be updated with the rest of the sources.

**Comment by ylep** [comment]
> `bv` does work from the sources. Does it not ?

I was not clear enough: it *does* work the way you describe: only inside of a given casa-distro environment. It *does not* work in an independently cloned casa-distro source directory (e.g. `~/casa_distro/sources`), whereas `casa_distro` and `casa_distro_admin` *do* work in that scenario, provided that you set `base_directory`. In my view this places it in a different category, and would justify putting it in a different directory. But that's nitpicking, I am also fine with leaving it in `bin`.

**Comment by denisri** [comment]
We could make it work using a `CASA_DEFAULT_ENVIRONMENT` env variable (we used it at a time I think in `casa_distro`, but it seems to have disappeared) if we want `bv` to work this way. It's not very very useful in this situation I admit.

**Comment by ylep** [comment]
>  or I write another command just to run the GUI, which would perform detection of the installation paths.

I would be in favor of that second option, to keep a clearly defined role for each command.

**Comment by ylep** [comment]
Summary of what we just decided:

```
casa-distro
├── bin
│   ├── casa_distro
│   └── casa_distro_admin
└── cbin
    └── casa_container  -> setup_dev, setup_user, configuration_gui
```

**Comment by denisri** [comment]
It's a bit difficult *not* to install casa_distro, casa_distro_admin and bv commands inside a container: it would require to "build" differently on a host or container system.
For now I instead print a clear error message when commands are used from the wrong side.

**Comment by ylep** [comment]
>  it would require to "build" differently on a host or container system.

Well my argument was that we should not need to *build* casa-distro: we would always use it from its sources, be it on the host or on the container. But I am fine with an error message too.

**Comment by denisri** [comment]
Oh, yes it could be this way. But it would require users to manually add paths to sources to actually get casa_distro commands. As people prefer...?
