### ISSUE TITLE
Compile Singularity with the seccomp library

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#211]
Singularity is giving a warning that worries me a bit:

```WARNING: Not compiled with seccomp, fakeroot may not work correctly, if you get permission denied error during creation of pseudo devices, you should install seccomp library and recompile Singularity```

This has not caused any real issues for me (I could successfully build base images and user images), but to be on the safe side, maybe we should add this library when we compile Singularity?

**Comment by sapetnioc** [comment]
I am in favor of adding a library that can provide more features to Singularity. However, I do not know if this library will be included in our packages. If not, we may have to add a dependency on the package (and change installation instructions). If yes, we will have to assess possible conflicts if this library exists in another Debian package.

**Comment by denisri** [comment]
Is it a compile-time dependency only, or also a run-time dependency ?
Anyway we need to add it in the images we use to create the `.deb`, not only in the package dependencies.

**Comment by ylep** [comment]
`libseccomp2` is a required package in Debian/Ubuntu, so we should not have a problem with dependencies. It should be enough to add `libseccomp-dev` to the image used to build Singularity.

**Comment by sapetnioc** [comment]
Can you give me a way to get this warning with a Singularity command ?

Because I was able to use `singularity shell --security seccomp:/tmp/seccomp.json casa-dev-ubuntu-18.04.sif` to disable `mkdir`command (seccomp allows a program to restrict its allowed system calls) without warning.

No more warning for `singularity shell --fakeroot casa-dev-ubuntu-18.04.sif`

**Comment by ylep** [comment]
Hum, I found the issue on https://new.brainvisa.info/builds/job/disco-minimal-nightly/15/ which is... my own workstation, which is not using the singularity packages that we build...

Hold on for a second, I will install the packaged Singularity and try to reproduce the issue...

**Comment by ylep** [comment]
Ahem, the Singularity debs do not have this issue. This must have been a problem with my own local build of Singularity. Sorry for wasting your time...
