### ISSUE TITLE
paramiko is not installed for python3

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#212]
it should be added in dev images

**Comment by sapetnioc** [comment]
Is it only for dev or is it necessary for soma-workflow clients? In the
second case, it must be installed in run image.

>

**Comment by denisri** [comment]
It's necessary for soma-workflow clients.
As far as I remember, python3 runtime tools are installed in the dev image for now (as long as the officiel release is using python2). I have added it in the dev image creation, but not rebuilt the images yet (I have other changes in the way).
