### ISSUE TITLE
CASA_BRANCH is "bug_fix" instead of "master"

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#213]
In a dev environment installed for `branch=master`, in the container I get a `CASA_BRANCH` envar with the value `"bug_fix"` where I expected `"master"`. Is it intentional or a remaining of the obsolete naming ?

**Comment by ylep** [comment]
I think that `CASA_BRANCH` is only used in bv_maker.cfg, so if we change `bv_maker` to recognize `master` instead of `bug_fix`, we could fix this historical anomaly

**Comment by ylep** [comment]
The components are not recognized anymore in the `build` section of `bv_maker.cfg`, I suspect the problem may be related to the change of "$CASA_BUILD" from `bug_fix` to `master`.

```shellsession
$ /volatile/bv/cron/disco-minimal-ubuntu-18.04/bin/bv bv_maker configure
$ cmake -DRUN_MATLAB_TESTS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DBRAINVISA_PACKAGING_THIRDPARTY:BOOL=OFF /casa/host/build
-- Add specific paths for Ubuntu distribution
-- Add specific paths for CEA - I2BM research labs
-- Configuring done
-- Generating done
-- Build files have been written to: /casa/host/build

bv_maker summary:
OK          step configure: /casa/host/build, started: 2021/01/19 15:15, stopped: 2021/01/19 15:15
All went good.
$ /volatile/bv/cron/disco-minimal-ubuntu-18.04/bin/bv printenv CASA_BRANCH
master
```

This issue has appeared on all the nightly builds, see e.g. https://new.brainvisa.info/builds/job/brainvisa-master-ubuntu-18.04/116/

**Comment by denisri** [comment]
What's the `bv_maker.cfg` for this build ?
If components have been set directly in the `bv_maker.cfg`, with svn branches referred as `$CASA_BRANCH` in the repository URL, then yes it may have changed.  We don't really have means to change such URLs. Those handled in components_definition.py have been "duplicated" under both names, but components outside this perimeter have to be changed by hand.
Do we need to revert the changes ?
We could also perhaps translate the `CASA_BRANCH` envar inside `bv_maker` (by replacing its value `"master"` -> `"bug_fix"`) but this would not be a clean long-term solution...

**Comment by ylep** [comment]
`bv_maker.cfg` for the `brainvisa-master-ubuntu-18.04` is the default `bv_maker.cfg` for the `brainvisa` distro:

```ini
[ source $CASA_SRC ]
  brainvisa standard $CASA_BRANCH

[ build $CASA_BUILD ]
  default_steps = configure build doc
  make_options = -j16
  build_type = Release
  packaging_thirdparty = OFF
  clean_config = ON
  clean_build = ON
  test_ref_data_dir = $CASA_TESTS/ref
  test_run_data_dir = $CASA_TESTS/test
  brainvisa standard $CASA_BRANCH $CASA_SRC
```

**Comment by denisri** [comment]
Has `bv_maker` run twice (to update components_definitions.py first, then run again to use it) ?

**Comment by ylep** [comment]
`bv_maker` does not update itself anymore:

```
$ PATH=/usr/local/bin:/usr/bin:/bin CASA_BASE_DIRECTORY=/volatile/a-sac-ns-brainvisa/bbi_nightly SINGULARITY_TMPDIR=/volatile/tmp BRAINVISA_PUBLISH_SERVER=new.brainvisa.info /volatile/a-sac-ns-brainvisa/bbi_nightly/brainvisa-master-ubuntu-18.04/bin/bv_maker sources configure
$ svn cleanup /casa/host/src
$ svn propset svn:externals --file /casa/host/src/bv_maker.externals /casa/host/src
property 'svn:externals' set on '.'
$ svn commit -m '' /casa/host/src
$ svn update /casa/host/src
Updating '.':
At revision 3.
$ cmake -DCMAKE_BUILD_TYPE:STRING=Release -DBRAINVISA_PACKAGING_THIRDPARTY:BOOL=OFF /casa/host/build
-- Add specific paths for Ubuntu distribution
-- Configuring done
-- Generating done
-- Build files have been written to: /casa/host/build

bv_maker summary:
OK          step sources: /casa/host/src, started: 2021/01/19 18:52, stopped: 2021/01/19 18:52
OK          step configure: /casa/host/build, started: 2021/01/19 18:52, stopped: 2021/01/19 18:52
All went good.
```

It is stuck at version https://github.com/brainvisa/brainvisa-cmake/commit/fe728b19fef6a16eca68b4ec0b5204b1d1e3b3a8 and is unable to update itself because it cannot do so with `CASA_BRANCH=master` (casa-distro has been updated).

I will change `bv_maker.cfg` temporarily to allow it to update itself, and close this ticket if that works.

**Comment by denisri** [comment]
Ah I see. I don't see an easy solution, apart from reverting the `CASA_BRANCH` envar to `bug_fix`, and after a time sufficiently long for every developer to update, change it again to `master`. the problem here is that `casa-distro` has been updated but `brainvisa-cmake` has not, whereas it would need to be updated first.

**Comment by ylep** [comment]
I fixed it by opening a shell in each container and manually running `CASA_BRANCH=bug_fix bv_maker sources configure`.

@denisri @sapetnioc we should probably inform the other developers to run that command during the meeting tomorrow morning
