### ISSUE TITLE
casa_build_host_links is not run during the first bv_maker

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#216]
I had to run `bv_maker` a second time in order to get the links. I guess that it must be an issue when using `/casa/brainvisa-cmake` and/or `/casa/casa-distro`, as is the case during the first run in an empty environment.

**Comment by sapetnioc** [comment]
Just to confirm that I had the same behaviour.

**Comment by denisri** [comment]
Isn't it because the images are outdated and contain an old bv_maker ?
I have rebuilt them some minutes ago, and I'm rebuilding them again to fix another issue (paths in #80), we can try using those. I'm currently working on the imaged themselves and haven't done a full build in them yet.

**Comment by sapetnioc** [comment]
I will have to set Python 3 by default in `cati_platform` distro `bv_maker.cfg` file. Therefore a new image creation will be necessary. After that, I will try a compilation from scratch and will be able to see if the bug is still here. But I already used a quite recent image.

**Comment by denisri** [comment]
it's because casa_distro is not installed any longer and cannot be called during the build.

**Comment by denisri** [comment]
Docs won't be built either, and we don't have an easy reliable way to find out where sources are... maybe using the pythonpath.

**Comment by denisri** [comment]
we can use `casa_container` in containers.
