### ISSUE TITLE
Install of dcmdjpeg for qualicati

### ISSUE THREAD

**Issue by rbonicel** [brainvisa/casa-distro#217]
Hello, 

We found an issue with some dicom files that needed the library "dcmdjpeg" to be properly decoded and processed through our quality control software. In anticipation of future usage within casa_distro3, could you please install "dcmdjpeg" library in casa_distro3 image for us to use ?

Thank you very much for your help.

Robin

**Comment by sapetnioc** [comment]
This is a first request for a software that is required for `cati_platform` distro but not for other distros. This raises the question of having the possibility to customize user images per distro. I think it could be an interesting feature especially if we have to build distros for other software. I am thinking to Intranat and Populse Mia.

**Comment by denisri** [comment]
Is is really specific to `cati_platform`, or may it happen for anyone dealing with arbitrary dicom files ? I would think it would be a good idea to include it in standard run images. The rest of @sapetnioc comment is valid, of course.

**Comment by denisri** [comment]
`libdcmjpeg.so.12` seems to be part of the `libdcmtk12` package which is already installed in all casa-distro 3 images. what is exactly missing ?

**Comment by sapetnioc** [comment]
Since @rbonicel has left and nobody is still asking for this change in CATI, I close it.
