### ISSUE TITLE
Both "run" and "user" images get the type "run"

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#221]
It seems intentional since the `casa_distro_admin create_user_image` command documents it as a "run image" at many places, but there is a confusion in our notions in casa-distro on what we called "run" images (runtime libraries without brainvisa, to run test and to be used as the base for "dev" images, and what we generally call "user" images (containing brainvisa programs, what users actually download). As a result in the .json files going with them, both kind of images have the "type" variable set to "run", which doesn't provide a convenient way to distinguish and filter them.
Do we call them "officially" "user images", or do we rename the other run images, or do we stick with this ambiguity ?

**Comment by sapetnioc** [comment]
For me it is a mistake. I believe we have four image types :

- **system** for a standard system images not modified but with metadata and adapted to be able to build other images automatically
- **run** used internaly as base image for dev and user images
- **dev** image containing developement dependencies and used for building development environments
- **user** images targetting end users and composed of a run image with an installation of a dev environment.
