### ISSUE TITLE
change http links to https

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#225]
in all doc pages we have to change http://brainvisa.info to https://brainvisa.info

**Comment by sapetnioc** [comment]
There is a carousel for Constellation define in `bv_build_web_14.py`. The code is using static images with relative URLs and two absolute links that are not on the new website today. Can anyone know where to find them and how to publish them :

http://brainvisa.info/doc/constellation/video/connectivity_profiles.ogg
http://brainvisa.info/doc/constellation/video/small_brains.ogg

**Comment by sapetnioc** [comment]
There is a lot of `http://brainvisa.info...` in `changelog.html`. Should we keep them or change them to `https://brainvisa.info` ?
I think we should keep them because they are like historical tales.

**Comment by sapetnioc** [comment]
Does anyone knows if `download_template.html` is still used in web project ? I cannot find any reference to it and I am about to delete it (and some other related files).

**Comment by sapetnioc** [comment]
In the [download page](https://new.brainvisa.info/web/download.html), there are several absolute reference to `http://brainvisa.info/download`. I think they can be removed because there is PHP generated list of selected download items just after. If ever there is a need to reference download directory, it is possible to use `/download/` as target (if possible with Sphinx).

**Comment by denisri** [comment]
> There is a carousel for Constellation define in `bv_build_web_14.py`. The code is using static images with relative URLs and two absolute links that are not on the new website today. Can anyone know where to find them and how to publish them :
> 
> http://brainvisa.info/doc/constellation/video/connectivity_profiles.ogg
> http://brainvisa.info/doc/constellation/video/small_brains.ogg

Uh oh. The site has probably erased and rebuilt since we put these files there. I don't remember where we have them, I hope it was not the only copy of them...
We lack a system to store such large files that we didn't want to get in svn. Not sure git-lfs is a very good solution either.
There are a few other videos in the web site that are not under svn, but I still have those.

**Comment by denisri** [comment]
> There is a lot of `http://brainvisa.info...` in `changelog.html`. Should we keep them or change them to `https://brainvisa.info` ?
> I think we should keep them because they are like historical tales.

It depends if they are dead links, or if switching to https would make them work.

**Comment by denisri** [comment]
> Does anyone knows if `download_template.html` is still used in web project ? I cannot find any reference to it and I am about to delete it (and some other related files).

It was part of the former download page building procedure: this page was not directly seen in the web site, but used and postprocessed by a script (bv_build_web_downloadpage.py) to build tables with available downloads - more or less what you have rewritten in php, but this was for the installer. Thus is it still visible in the "downloads for older versions" page.

**Comment by denisri** [comment]
> In the [download page](https://new.brainvisa.info/web/download.html), there are several absolute reference to `http://brainvisa.info/download`. I think they can be removed because there is PHP generated list of selected download items just after. If ever there is a need to reference download directory, it is possible to use `/download/` as target (if possible with Sphinx).

If we want to hide the actual download directory URL, yes. Do we ? I'll try the relative links also.
