### ISSUE TITLE
procedure for toolboxes installation

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#229]
Some external toolboxes such as https://github.com/MecaLab/Brainvisa-Diffuse (from Marseilles) are currently not shipped with the BrainVisa distribution, but are designed to be added on top of an existing installation. This was OK when Brainvisa was published as an installer which unzipped files on a writable filesystem: toolboxes just had to unzip their files into the same filesystem.
Now this could still work inside a VirtualBox VM, but will not work with a singularity install which contains BrainVisa files in a read-only filesystem.
How can we handle this ?
* include every toolbox in the main distribution ?
* allow toolbox installation only in read-write containers (VirtualBox, maybe later docker) ?
* publish a procedure to convert singularity images / installs into wrtiable images ?
* use overlays - quite convenient but with a major drawback: only one instance can run at a given time ?
* ask toolbox developers to rebuild a complete BV distribution including their toolboxes (as have been done for Intranat in Grenoble) - but then if several labs publish their toolboxes, we will never get all of them in a single install ?

I think we must have a reflection about it, and propose a procedure to external toolbox developers when we release BV 5.

**Comment by denisri** [comment]
A few more options:
* ask users who need to install additional toolboxes to convert to a writable sandbox image, then unzip the toolboxes inside the sandbox directory
  * pros: flexible, quite easy
  * cons: cannot be updated later if updates are available
* provide a procedure for users to re-install the /casa/install contents into a mounted directory, then unzip toolboxes into this host, writable filesystem directory.
  * pros: the "system" image can be updated
  * cons: the brainvisa distribution (`/casa/install/` directory) is duplicated, using some disk space for nothing

**Comment by sapetnioc** [comment]
We may provide a casa-run image with a procedure to mount a read/write `/casa/install` directory. The downloading of the install directory could be part of the setup process. If the run image is distro independant, users will have to select a distro (e.g. an install directory to download) during setup. But we can provide a run image for each distro that woul contain an hardcoded install directory download URL.

**Comment by denisri** [comment]
It could be this way, yes. But this would need to significantly revise our strategy and tools for user images creation, upload, setup. The setup would act a little bit like an installer, and download the given set of tools. And thus do we still provide the brainvisa-<version> user images as they are today, or switch to this setup/download procedure for every user ?
And then, do we modify our codes now before the 5.0 release ?

**Comment by sapetnioc** [comment]
We said that this release would not support plugins. I am in favor of not taking the risk to add a delay to the release. We can target this solution (that does not seem very difficult to implement) for the next release. In the meantime, users will have to use VirtualBox (since it seems to finally work now).

**Comment by denisri** [comment]
It's not difficult to implement, actually. I'm playing with this in the branch "rw_install", where I have added 2 options to `setup_user`:
1. `rw_install`: installs a full user image, but copies the `/casa/install` directory into `/casa/host/install` (seen by the host, thus read-write)
2. `distro`: if distro is specified, downloads a brainvisa distro archive (zip) from the web site to `/casa/host/install`, regardless of what is actually in the image
The paths are adapted then to search in `/casa/host/install` instead of `/casa/install`

#

1. could be used to unpack a regular, self-contained user image without the need for a network connection. It consumes more disk space of course since all the brainvisa code is duplicated.
2. could also be used from an  "empty" run image to download the given distro (user image not needed). The setup could perhaps be done several times with several distro names in order to install several toolboxes (?), it would thus act a little bit like an installer. This would require to include again casa-distro in the run images (we have just removed it.)

The download/install code is already in the branch rw_install (testing). The `create_image` code is not written yet but would not be difficult (zip the contents of `/casa/install`, create a json file with a md5 sum in it, upload to the web site)
