### ISSUE TITLE
Add tox to casa-dev images?

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#23]
As discussed with @denisri, we may want to add [tox](https://tox.readthedocs.io/) to the casa-dev images in order to have a simple way of running the tests locally under multiple version of Python, in the same way that they run on Travis.

You may want to take a look at [brainvisa-cmake/tox.ini](https://github.com/brainvisa/brainvisa-cmake/blob/master/tox.ini) and [brainvisa-cmake/.travis.yml](https://github.com/brainvisa/brainvisa-cmake/blob/master/.travis.yml) to see what I mean.

If we decide to use it for other core projects, we could either:

1. install it in the casa-dev images,
2. or, let developers that want to use it install it locally with `pip install --user tox` (then we need to add `/casa/home/.local/bin` to the `PATH`).

Provided that we are not going to make `tox` mandatory like `pre-commit`, **I would vote for solution 2**.

**Comment by Hboni** [comment]
Looks great! But does the solution 2 needs dev to run tests on a writable image (to be able to install tox no)? 

In my opinion, if we have `tox.ini` files in some core libraries (maybe in all of them in the future), and to help dev to use it generally (not only for git projects), I would vote for the **solution 1**.

**Comment by ylep** [comment]
> the solution 2 needs dev to run tests on a writable image

Not necessarily, hence the need to use the `--user` option of `pip` and add `~/.local/bin` to `PATH`.

My argument against solution 1 is that it makes the images still a bit more bloated… but I agree that it makes it a little bit easier for developers.

**Comment by denisri** [comment]
Solution 1 is easier for developers, and images are already big so it won't make much difference.
