### ISSUE TITLE
bv should not accept casa-distro parameters after the command

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#231]
Reading an email from @denisri, I realized that `bv bash opengl=container` is allowed, and `bv` (actually `casa-distro run`) will interpret the `opengl=container` parameter.

I strongly think that we should *not* support this usage, because it is confusing and it forbids passing any argument containing `=` to the called command:

```shellsession
$ bv bash -c 'toto=titi printenv toto'
ERROR: run raised the following error:
Traceback (most recent call last):
  File "/volatile/bv/cea-master-ubuntu-18.04/src/development/casa-distro/master/python/casa_distro/command.py", line 337, in main
    result = command(*args, **kwargs)
TypeError: run() got an unexpected keyword argument 'toto'

Usage:
[...]

ERROR SUMMARY (details above): run() got an unexpected keyword argument 'toto':
```

It is true that we *do* have a workaround using `--`:
```shellsession
$ bv -- bash -c 'toto=titi printenv toto'
titi
```

Still, I think that this behaviour can be very confusing to users (who will not know about `--`). For that reason, I think that we should modify command-line argument parsing to **require that `key=value` parameters be passed *before* the command**. In other words, all arguments starting from the first one without a `=` should be passed verbatim to the command.

**Comment by denisri** [comment]
Yes that's completely true. We didn't take time to re-write the options parser for bv as it was planed initially.

**Comment by denisri** [comment]
The last commit avoids the confusion which motivated this ticket, but doesn't implement the "--arg" style we planed to implement.
