### ISSUE TITLE
Identification and cleanup of published test images

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#240]
To date, pushing a test user image raises two problems :
 - It appears in the download page as any final release (there is only one table)
 - Old test images are not deleted
 
I propose two modifications to  `casa_distro create_user_image` :
- add the possibility to customize the type of user images by adding a `type` parameter. This type would be `rc` by default (or `test` or any value different than `user`) and should be explicitely set to `type=user` to publish a final release. The type would be added at the end of default image name if different from `user`. 
- when uploading an image, delete automatically old images of the same distro + version + type. If we want to be able to have more than one image, we could add a parameter `max_uploaded_image=1` that would be the number of images to keep (keeping only the more recent ones). If we allow that, the command would have to deal with automatically adding an unused number to the default image name.

**Comment by denisri** [comment]
I'm mostly OK with that. I just wonder if `type == 'user'` is used in some places in the code or not (it's easy to check but I haven't done that yet). Fundamentally the test/rc images are not a different "type", they are used the same way. And for testing purpose, if they get a different type we don't really test the "user" type with rc images, thus, so we might leave bugs for the final user images ;)
The other option is to use a different directory for test/rc releases than the "official" download/ directory on the server, which would not mix "clean" and "work in progress" things.

**Comment by sapetnioc** [comment]
User images are not reused so I believe it is not used in the code. But is is used in the PHP code that creates the download links. This is why I proposed to use `type` (changing the type should remove the test images from the table immediately). But this is not a good reason, it is very easy to change the code to adapt the filter to another choice. I also thought of keeping `type=user` and adding a new item such as `category=rc` but I am not very happy with the name `category` and I have not been able to find a better one yet.

**Comment by denisri** [comment]
I was rather thinking of the `setup_user` command, and the configuration GUI.
`category` is not very clear, indeed. We could use something like `release_type`, or just filter in the php code if the version contains "rc" or "test".

**Comment by sapetnioc** [comment]
Discussion about images names and metadata are in #238
