### ISSUE TITLE
Arrange for singularity 3 to be installed on all NeuroSpin machines

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#242]

**Comment by denisri** [comment]
Installing singularity on the network with `--without-suid` is not a solution: it cannot use `.sif` files and converts them to sandbox directories every time we run singularity (plus probably other limitations, like in mount options I think). We must either install the `.deb` on every machine, or ask the files server admins to install singularity with sudo on the network filesystem.
I also wonder if local installs of the `.deb` might be wiped out by the automatic cleanup.

**Comment by ylep** [comment]
RITM0157471 created today

**Comment by ylep** [comment]
Finally Singularity version 3.9.5 is installed on all workstations in NeuroSpin since 23rd February :champagne:
