### ISSUE TITLE
Auto-configure mounts for usual paths (/media, /mnt, /neurospin, /i2bm, /volatile*)

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#245]
Having the usual paths auto-configured would make it easier for users to start using BrainVISA right away.

These paths should appear in `~/.config/casa-distro/casa_distro_3.json` so that they appear in the `bv` configuration GUI. What is the proper time to write these? I would say during `prepare_environment_homedir`, as that is guaranteed to run at least once before anything is launched in the container, including for shared environments.

**Comment by denisri** [comment]
Yes I guess `prepare_home` is the right place.
How do you handle the fact that those directories do not necessarily exist on the host system ? Add them in mounts only if they exist ? `/media` and `/mnt` are standard on linux hosts (but not on other systems), whereas `/neurospin`, `/i2bm` and `/volatile*` are clearly specific to Neurospin installation - is it OK to hard-code them in `casa-distro` ? (if others are OK it's fine for me).

I also want to point out that even for the same user, those directories do not always exist: in nework accounts we may have a `/volatile` (or `/volatile2`) directory on one machine but not on another. Moreover we may log an another system (Mac...) from the same account and not have `/mnt` or `/media`. Well it's not very annoying, these just print warnings when starting singularity (and we could remove them automatically in `casa_distro`).

**Comment by ylep** [comment]
> Add them in mounts only if they exist ?

Yes. Of course with a shared homedir like on NeuroSpin workstations the list, but as you say it is not very annoying to have nonexistent directories (e.g. `/volatile2`) as these just print a warning if they are missing.

Actually the warning is printed by `casa_distro` itself, while it removes the paths from Singularity options: I have added this bit of code because Singularity gives a fatal error if you try to bind-mount a nonexistent path.

**Comment by denisri** [comment]
So it's fine.

**Comment by denisri** [comment]
It's also possible to setup some mount points in the shared environment config (by hand, but they would be setup for all users), if we don't want to hard-code some neurospin-specific paths in casa-distro source code.
