### ISSUE TITLE
process hung in tests

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#247]
There are sometimes test processes hanging (there was one last night during bbi_daily, in soma-workflow tests). Should we setup a timeout mechanism for tests and kill such hung processes after a given time ?

**Comment by denisri** [comment]
There are several ways to do so:
1. using native `ctest`, in `CMakeLists`, using test properties, ex: `set_tests_properties(soma-workflow-simple PROPERTIES TIMEOUT 900)`
2. in `bv_maker` by transforming test commands in `brainvisa_add_test()` using a new timeout parameter
3. in `casa-distro`

All have advantages and drawbacks:
1: ctest
  - [+] already part of the `ctest` framework, already coded, thus seems the "natural" solution
  - [-] when test commands are extracted in `casa-distro/bbi_daily` (either to run dev tests or to get commands to run user image tests), we lose the timeout, unless we are able to read the timeout in each command (inside casa_distro `get_test_commands()`) and reproduce it by another means, but by doing this we disable the native ctest mechanism and re-do it our own way, thus it becomes somawhat pointless to use ctest
  - [-] the timeout cannot be adjusted to testing conditions (machine power etc)

2: bv_maker
  - [+] we have the possibility to tweak as we wish
  - [+] the test commands will already contain the timeout (using the `timeout` command on unix systems) so it would work the same way inside `casa_distro bbi_daily` or when run directly
  - [-] depends on the `timeout` command: OK on linux but would not work on Windows natively
  - [-] the timeout cannot be adjusted to testing conditions (machine power etc)

3: casa-distro
  - [+] we could set / overwrite global / individual timeouts in the environment config file, so it could be adjusted for specific test machines
  - [-] default timeouts would have to be defined in another config file - where ?
  - [-] when using `bv_maker test`, or directly `ctest`, in the build directory, we would have no timeouts.

Considering all this I would be inclined to chose solution 1. (or 2.)

**Comment by sapetnioc** [comment]
bbi_daily is not using ctest  so, as far as I understand, 1:  will not solve the problem.

For 2: I think we already started to go away from the possibility to come back to a native Windows version of BrainVISA. If ever we want to do so, replacing timeout command will not be our biggest challenge. 

I think that 2: seems to be the best option if we want each test to be able to define its timeout usage.

**Comment by denisri** [comment]
bbi_daily is not using `ctest` completely, but it's using it to get test commandlines. It parses the outputs of `ctest` to get commands, and could also parse the timeouts because `ctest` prints them, so it's possible to work this way. But I'm OK for 2.
Do we setup a default timeout (like 30 or 60 minutes) when tests do not specify one ?

**Comment by denisri** [comment]
Both 1. and 2. will work. A default timeout is used and taken from cmake/ctest variable, `DART_TESTING_TIMEOUT` which value seems to be 1500s (25 min): this seems enough for most tests. When they are longer it has to be configured in the CMakeLists.
