### ISSUE TITLE
In NeuroSpin the user-specific home is not in the correct directory

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#254]
In NeuroSpin the directory that is in the `PATH` depends on the host system, e.g. `/i2bm/local/Ubuntu-18.04-x86_64/brainvisa/bin`. Therefore, the user-specific home directory is created in `~/.local/share/casa-distro/i2bm_local_Ubuntu-18.04-x86_64_brainvisa`, which contains the name of the host system. This is unfortunate, because users that change host system lose their BrainVISA configuration. it would be better to share the configuration of BrainVISA regardless of the host system

In reality, the deployed BrainVISA lives in `/i2bm/brainvisa/brainvisa-cea-5.0.0`. It is accessed through two levels of symbolic links:

- `/i2bm/local/Ubuntu-18.04-x86_64/brainvisa` -> `/i2bm/brainvisa/Ubuntu-18.04-x86_64/brainvisa`
- `/i2bm/brainvisa/Ubuntu-18.04-x86_64/brainvisa` -> `../brainvisa-cea-5.0.0`

I suggest that we simplify this layout, by directly adding to the `PATH` a directory that is ignorant of the host system name, e.g. `/i2bm/local/brainvisa`, which would directly point to `/i2bm/brainvisa/brainvisa-cea-5.0.0`.

**Comment by denisri** [comment]
I did not realize that the full path was used to create the user home (although I knew it now you say it). Yes you're right, PATHS could / should point to a system-independent location now, but the network bash configs already pointed to system-dependent locations as Brainvisa use to be system-dependent. We should add a new path in the network config (I'm not sure if we still have access rights over them, there used to be a svn repository for these configs but I have somewhat forgotten...)
Or casa-distro should follow symlinks before determining the environment location ?

**Comment by denisri** [comment]
By the way, I don't think we have documented the way Casa-distro handles home directories, config files location etc. I guess we should make that clear somewhere, because users are starting to ask where are their files...

**Comment by ylep** [comment]
> Or casa-distro should follow symlinks before determining the environment location ?

I don't think we should do this, because we want users to keep their homedir when we switch from 5.0.0 to 5.0.1.



> I guess we should make that clear somewhere, because users are starting to ask where are their files...

I can add it to the doc

**Comment by denisri** [comment]
> I don't think we should do this, because we want users to keep their homedir when we switch from 5.0.0 to 5.0.1.

Yes that's true.

> I can add it to the doc

I'm currently writing a beginning of it (in casa-distro docs, at the beginning of the "technical" page) but I will leave it to you after a first draft, because you know the details better than I do ;)
I'll let you know when I'm done.

**Comment by denisri** [comment]
OK I have written something in the technical.rst file. Feel free to complete or correct...
