### ISSUE TITLE
Support passing host git credentials to container

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#255]
Working with private GitHub repositories requires to store a credential (i.e. a personal access token or an ssh key) in its home environment. It would be useful to be able to use these credentials from the container. To date, required files cannot be bound in `/casa/home` because Singularity is not well supporting a bind in a bound directory. They have to be copied on home directory of each environments.

**Comment by manuegrx** [comment]
I copied all the `.ssh` folder  from my home (with the public key added to GitHub)  on the casa home. 
I used ` ssh -T git@github.com` for testing my SSH connection in casa and it works . 


However, my my usernameand my password are required when I tried to update the sources with bv_maker (with an error message)

```Updating git repository /casa/host/src/catidb-client
$ git lfs install --skip-repo
Git LFS initialized.
$ git clone --branch main https://github.com/cati-neuroimaging/catidb-client.git /casa/host/src/catidb-client
Cloning into '/casa/host/src/catidb-client'...
error: unable to read askpass response from '/usr/local/bin/askpass-bioproj.sh'
Username for 'https://github.com': ````
