### ISSUE TITLE
image_id is not updated in the environments' casa_distro.json

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#264]
This leads to the wrong `origin_dev` being inserted in user images' metadata

**Comment by sapetnioc** [comment]
I am fixing that for `casa_distro pull_image`. Do anyone remember if there were other places where `image_id` was not updated ?

**Comment by denisri** [comment]
It's pull_image which actually changes images so I don't see another place we modify images and thus need to update environments. Anyway I think there is a tolerence when running a container, it checks that a newer image is compatible with the one referenced in the environment, and uses it transparently.
