### ISSUE TITLE
Undocumented dependencies for a new developement machine

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#279]
Starting with a brain new Ubuntu 20.04 (from Dell), the setup of a dev environment requires the following steps :

- [ ] Install `python-is-python3` package otherwise `casa_distro` command cannot start
- [x] Install `python3-distutils` package otherwise `casa_distro` fail to start because `distutils.spawn` is missing (in `singularity.py`).

**Comment by ylep** [comment]
I fixed the `distutils` dependency on the `master` and `brainvisa-5.0` branches. The absence of `/usr/bin/python` is a bit more problematic, I don't have a solution off the top of my head

**Comment by sapetnioc** [comment]
I think using `python3` will give us at least a few years before it become obsolete.

**Comment by ylep** [comment]
That change had been inadvertently reverted in the `master` branch, so I just re-applied it and fixed a few more shebangs that still pointed to plain `python`.
