### ISSUE TITLE
Symbolic links are followed during Singularity user image creation

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#284]
casa-distro uses the `%files` directive to copy installed files from the `install` directory into the user image. I just realized that `%files` follows symbolic links in this case, see https://sylabs.io/guides/3.8/user-guide/definition_files.html#files.

This is especially problematic for the `/casa/install/bin/python` symlink, which is copied from the host... :fearful: 

We may switch to using `%setup` to control the copy, or maybe a cleaner alternative is to do a multi-stage build.

**Comment by denisri** [comment]
Moreover some symlinks are here for a reason, and end up with many duplicated files in the installed packages (such as libraries in `lib/`)
