### ISSUE TITLE
There should be a way to customize the singularity container shell environment

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#290]
**Is your feature request related to a problem? Please describe.**
When running `bv` for a singularity container with a command (`bv_maker`, `brainvisa` or anything else except `bash`), it is run as a non-interactive shell, and no personal startup file is read (`$HOME/.bashrc` and `$HOME/.bash_profile` are not used). However if the user has customized his environment (`PATH`, `PYTHONPATH` for instance) there is no obvious way to set it automatically for commands run through `bv`: they will run in the wrong environment, unless the user runs `bv bash` interactively, then runs the commands inside.
This feature is needed if the user has, for instance, installed another version of some libraries, and needs to make them used systematically.

**Describe the solution you'd like**
We should provide a user-customizable entrypoint script used by `bv`, either
1. source` $HOME/.bash_profile` or `$HOME/.profile` like a login shell
2. use another "known and documented" file like `$HOME/.casa_distro_rc`
This file should be sourced from the singularity entrypoint after other environment scripts (`/casa/environment.sh`, `/casa/devenvironment.sh` and `/casa/start_scripts/init.sh` are already sourced when they exist)

Which solution would be better ?

**Describe alternatives you've considered**
For now I could trick the system by mounting a directory containing an `init.sh` script in `/casa/start_scripts`, because this specific script is run if it exists; however it is not a good solution because 1) it's not documented, 2) it's not convenient, 3) it's an internal hook used in some configurations of `casa_distro` startup (to add some nvidia libs for instance), which can interfere with it

**Comment by sapetnioc** [comment]
A simpler solution could be to set the `ENV` variable to ask `sh` to read a standard file (could be `.profile` ?). For instance, if you create a `/casa/home/.profile` in the container, the following command allows to read it from the host:

```
{base_directory}/bin/bv env ENV=/casa/home/.profile sh
``` 
However, it does not work with `bash`. Therefore we could want to use `.bashrc` instead but it can be confusing because the content of this file may not be compatible with `sh`. I would prefer to add the sourcing of `.profile` in the generated `.bashrc` and to always use `.profile`.

**Comment by denisri** [comment]
I tried the `ENV` and `BASH_ENV` variables but they don't seem to do anything, or maybe you need to run `bv env something` instead of `bv something`, which is not what we want / need because we generally run commands through the symlinks to `bv` in `<environment>/bin/`.

The entrypoint shell is `sh` ? I didn't really know about it - thus any bash-specific script is disqualified.
So do we go for `.profile` ? It would be sourced automatically (if it exists) from the entrypoint, thus in addition to `.bashrc` for an interactive shell, is it OK ? (and we need to rebuild images to get it work)

**Comment by denisri** [comment]
I have built and published new run/dev images with this fix.
