### ISSUE TITLE
No icon enabled UTF8 font in PyQt

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#293]
**Describe the bug**
UTF8 fonts comes with many useful characters that can be used as icons. These can be used on a standard Ubuntu 20.04 system by just installing PyQt. However, in current casa-distro image, an empty square is displayed. I do not know yet how Qt manage fonts and what to install to solve this problem. But it would be very interesting to be able to use such characters to build some GUI elements.

**To Reproduce**
Try the following code:
```
import sys
from PyQt5 import Qt

app = Qt.QApplication(sys.argv)
b = Qt.QToolButton()
b.setText('📂')
b.show()
app.exec_()


```

**Expected behavior**
Show a button containing a folder icon

**Screenshots**
Here is the expected result:
![image](https://user-images.githubusercontent.com/3062350/142995393-933cae73-9188-4a10-adc7-505a4d6e6e2b.png)

Here is what we get with casa-distro:
![image](https://user-images.githubusercontent.com/3062350/142995705-2b8fd453-1ef8-4048-996e-65f8e7282fd5.png)

**Environment:**
 - Engine: Singularity
 - Version of BrainVISA: images `casa-dev-5.0-5.sif` and `casa-dev-5.1-1.sif`

**Comment by sapetnioc** [comment]
In the sample code, the value of ̀`b.font().toString()` is `'Ubuntu,11,-1,5,50,0,0,0,0,0'` on my Ubuntu 20.04. There are some files related to Ubuntu font that belong to the package `fonts-ubuntu`. I will see if installing this package in the image is enough to solve the issue.

**Comment by denisri** [comment]
I can't copy/paste the character in your sample code. How do you type it ?

**Comment by sapetnioc** [comment]
I did copy-paste it from the web and I can copy-paste the code in my editor (or in IPython). However, the same string can be written as an hex code : `'\U0001F4C2'`.

**Comment by sapetnioc** [comment]
It is not enough to install the font package. I do not know how Qt choose the default font for application and what is the link with the system configuration but I suppose it is there that lies the solution.

**Comment by sapetnioc** [comment]
Found a solution. Using `fc-list -v` one can see the charset supported by each font. I suppose this is a sort of bit map with character codes. I saw that, on my host system, at least two fonts had a much bigger charset than others : noto and droid. I just installed the package `fonts-noto-color-emoji` and the folder is displayed correctly in the container. This package (or another equivalent ?) shoud be added to our next images.

**Comment by denisri** [comment]
OK.
Does it also work on ubuntu 18.04 ?

**Comment by sapetnioc** [comment]
yes, exactly the same with Ubuntu 18.04 dev image.

**Comment by denisri** [comment]
I have this `fonts-noto-color-emoji` package installed on my host system (ubuntu 18.04) and it still displays a square (no container). But we can install the package anyway. I'm about to rebuild some images.

**Comment by denisri** [comment]
(OK I could make it work by forcing the font to "`Noto Color Emoji`" - maybe it becomes automatic after a reboot or only on ubuntu 20)

**Comment by denisri** [comment]
New images have been uploaded.
