### ISSUE TITLE
should casa-system images still exist ?

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#294]
I realize I did not use a "`casa-system`" image to build the latest run and dev images, but have built the run image from a raw ubuntu image (imported from dockerhub). It performed without error, and the images seem to work well.
Now I realize that, I'm building a `casa-system` image, which produces `casa-system-<version>.sif`, and this image seems identical to the raw system `ubuntu-<version>.sif` (same size, diff says they are identical). Is this normal or am I missing anything ?
If it's normal, then why not drop this `casa-system` intermediate image, which is documented and used by default by `casa_distro_admin create_base_image type=run`

**Comment by sapetnioc** [comment]
The only reason is to be consistent with VirtualBox where the building of a base system image is a manual time consuming step. This should be the only step that differ for image creation between Singularity and VirtualBox.
