### ISSUE TITLE
At the installation bug at the first command "singularity run -B bla bla.."

### ISSUE THREAD

**Issue by clarafischer** [brainvisa/casa-distro#310]
When we follow the tuto to install a new casa, the first command `singularity` does not work on a laptop (install CEA and no CEA, Julie had the same problem). The command return :
`/usr/local/bin/entrypoint: 34: .: cannot open /usr/local/fsl/etc/fslconf/fsl.sh: No such file`
But /usr/local/fsl/etc/fslconf/fsl.sh exist and I can open it.

I can make it work by putting `sudo` before but after bv_maker won't work, it return :
`PermissionError: [Errno 13] Permission denied: '/casa/host/src/bv_maker.cfg'
`
I suppose because of the sudo all my directories where `root` so I change for me to be the owner of the directories and it worked.

I try with the image `casa-dev-5.3.8.sif` and my version of singularity is `3.9.5-bionic`. I had already a casa with an image casa-dev-5.0.11.sif and I had no problem during the installation.

Any ideas why it is not working any more ?
Thanks !

**Comment by denisri** [comment]
Hi,
You mean when installing a new environment using `singularity run -B <env_directory>:/casa/setup casa-dev-5.3.8.sif ...` ?
I don't have this error, and I don't know where this reference to FSL is. Maybe there is a home directory and home config (`.bashrc`/`.bash_profile`/`.profile`).
That's probably the clue: by default singularity shares the user and his/her home directory, thus the `entrypoint` script sources the user host `.profile`. Later, `bv` / `casa_distro` uses a different home dir to avoid this kind of problem, but during setup it's the "raw" singularity which is used.
Here `/usr/local/fsl` is probably used in your host `~/.profile`, and this directory exists on the host system, but obviously not in the casa-distro image.
Maybe try adding `-H /tmp` (or another empty directory) to the singularity command, to use a different home directory ?

**Comment by sapetnioc** [comment]
Instead of using `-H /tmp` it could be possible to use `-c` (or `--contain`) that prevent singularity to mount directory by default.

**Comment by clarafischer** [comment]
Hello, sorry for the delay.
Yes Denis it was when I do `singularity run -B <env_directory>:/casa/setup casa-dev-5.3.8.sif ...`. And yes you are right I have install FSL on may laptop so I have `/usr/local/fsl`in my `~/.profile`.
I try Yann's solution `-c` and it works well ! Thanks a lot, may be it should be mention on the tuto because I don't think I am the only one to have stuff in the `~/.profile`.

**Comment by denisri** [comment]
I have added the option in docs and in the website (https://brainvisa.info/web/download.html).
