### ISSUE TITLE
Existing releases rely on /usr/bin/python, which is missing on newer distros such as Ubuntu 22.04

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#317]
**Describe the bug**
Existing releases such as BrainVISA 5.0.4 do not work out of the box on Ubuntu 22.04, because host scripts (`bv` and `casa_distro`) rely on a `#!/usr/bin/env python` shebang, whereas the default install only has a `python3` executable on the `PATH`.

**Expected behavior**
We could  change the shebang to `#!/usr/bin/env python3`, or if we want to retain compatibility with Python 2-only systems, we could autodetect the version to use at setup time.

**Environment:**
 - Engine: Singularity
 - Version of BrainVISA 5.0.4

**Comment by denisri** [comment]
done
