### ISSUE TITLE
Configuration directories ~/.brainvisa and ~/.anatomist are difficult to find

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#318]
NeuroSpin users have difficulties finding the .brainvisa / .anatomist directories, .because they are not aware of the `~/.local/share/casa-distro/i2bm_local_brainvisa/home`. Most docs simply refer to `~/.brainvisa` and `~/.anatomist`.

Maybe we should create a symlink to these directories at setup time :

    ~/.local/share/casa-distro/i2bm_local_brainvisa/home/.brainvisa -> ~/.brainvisa/
    ~/.local/share/casa-distro/i2bm_local_brainvisa/home/.anatomist -> ~/.anatomist/

**Comment by sapetnioc** [comment]
Are all NS brainvisa users still using `/i2bm/brainvisa/etc/profile` ? If yes we may create the links here (after checking the existence of the target directories) instead of in setup ?

**Comment by sapetnioc** [comment]
I just realized that my suggestion has a drawback. The links would not be created immediately after the setup but only when a new shell is started. On the other hand, it would allow create the links for users who already have a home directory created.

**Comment by denisri** [comment]
Creating links to the host `~/.brainvisa` etc would completely share all configs for all brainvisas. On one hand it is what most users expect and want for the simplest use cases, on the other hand it would probably insert container paths (`/casa/somathing` and/or `/host/something`) in a host config. As long as programs are only used in containers (which is what we always do nowadays) and mount points are correctly configured in all environments, it should be OK, but not totally clean...
All in all, I think I'm OK for it.
What should we share then ?

- [ ] `~/.brainvisa` ?
- [ ] `~/.anatomist` ?
- [ ] `~/.soma-workflow` ?

Others ?

**Comment by denisri** [comment]
> Are all NS brainvisa users still using `/i2bm/brainvisa/etc/profile` ?

Not in containers...
