### ISSUE TITLE
Qt applications crash under X2Go in the casa-run-5.3 image

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#321]
**Describe the bug**
Qt applications crash under X2Go in the casa-run-5.3 image, with error messages about xcb.

```
qt.qpa.gl: QXcbConnection: Failed to initialize GLX
[...]
qt.qpa.xcb: QXcbConnection: XCB error: 1 (BadRequest), sequence: 169, resource id: 408, major code: 130 (Unknown), minor code: 47
```

**To Reproduce**
1. Open an X2Go session
2. Launch any Qt programs: `anatomist`, `brainvisa`, even `bv`
3. Resize the window a few times to trigger refresh events, soon you the app will freeze and even the whole X2Go session may stop responding, partially or totally.

**Environment:**
 - Engine: Singularity
 - Version of BrainVISA: 5.1.0rc1

**Additional context**
The issue appears because X2Go uses a very outdated code base of the X server. I will try to implement the workaround described here: https://wiki.x2go.org/doku.php/wiki:development:glx-xlib-workaround which actually implies reincorporating a software-rendering libGL in the image.

**Comment by ylep** [comment]
I tried reusing the old `libGL.so` that we had in the `casa-run-5.0` image , with mixed results:
- the xcb error messages persist: `BadRequest`, `BadWindow`... as well as the initial `Failed to initialize GLX` message.
- but, the “good” thing is that I could not get `brainvisa` or `anatomist` to crash.

I will now try to build a libGL within the `casa-dev-5.3` image to see if it gives better results.

**Comment by ylep** [comment]
Now I just realized that one of my X2Go servers crashes, but not the other. I have to redo all tests, which will have to wait until tomorrow.

Both servers are running the same Ubuntu 18.04 and the same MATE desktop environment, but they have different graphics cards and different NVidia drivers:

- the Quadro K620 with 470.161.03 does not crash
- the RTX A5000 with driver 510.108.03 crashes.

**Comment by denisri** [comment]
I agree.

**Comment by denisri** [comment]
OK if the test is **fast**. In many situations we run these containers many times for quite short tasks so the OpenGL test should not take a noticeable time (or be done only in graphical sessions where a X server is connected, or something else).

**Comment by ylep** [comment]
`glxinfo` is a really slow command... a quick test gives about 500 ms of overhead (whereas the current overhead for running a no-op like `bv true` on my machine is 421 ms). That overhead may be acceptable for launching a full-fledged GUI (`brainvisa` or `anatomist`) but it is too much for simple command-line tools.

Unless we modify `bv` to e.g. set `gui=True` mode for GUI commands only, this is not really a practical solution.

**Comment by sapetnioc** [comment]
What do you think of an option such as `gui=remote` that would be like `gui=True` but launching `glxinfo` to avoid problems with x2go ?

**Comment by denisri** [comment]
It's possible but it would not be automatic, which would be almost the same as using `opengl=software` (thus a bit redundant). The question was rather if we could detect this situation automatically without the user bothering about it, but it seems to have a cost...

**Comment by ylep** [comment]
Considering that the `glxinfo` autodetection would only fix an issue with a really old version of X2Go (4.0), I don't think it is worth it. BrainVISA is not the only software to have problems under X2Go 4.0...
