### ISSUE TITLE
Casa-distro images 5.3 (Ubuntu 22.04) are incompatible with old linux kernels

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#324]
Running images on old linux kernels (RHEL7) result in Qt libraries "not found" in the image when running Qt applications.
We have run into this problem in our institution computing center, and it has also be reported here: https://github.com/brainvisa/brainvisa.github.io/discussions/121#discussioncomment-4658379

The computing center support has suggested that this may be due to ABI tags in the Qt libs which check for a kernel ABI version which is not found, but in most cases specific kernel features are not needed (most of the system otherwise runs...), and that we may just remove the ABI tags from the Qt libs. This needs patching Qt system libs in the images (and thus rebuild images).
We are currently trying this solution (but it's not tested yet).

**Comment by denisri** [comment]
I have rebuilt new images with the ABI tag stripped (in principle), but I could not test them so far because I cannot make the container system work in the computing center any longer at the moment. We'll test next week.

**Comment by denisri** [comment]
d01062584d6f7296e1244f12881646f144898047 seems to have fixed the problem in the computing center: I can now use Qt and PyQt in images 5.3 there.
I don't know if other libraries than Qt could be affected by this problem.

**Comment by ylep** [comment]
@denisri I have rebuilt the images with the software-only libGL (https://github.com/brainvisa/casa-distro/pull/322), should I rebuild them with your fix (https://github.com/brainvisa/casa-distro/commit/d01062584d6f7296e1244f12881646f144898047) before pushing them to brainvisa.info?

**Comment by denisri** [comment]
This seems to be fixed. If not, we will reopen the ticket.
