### ISSUE TITLE
In dev environment, casa_distro[_admin] -h is not working

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#327]
Since `casa_distro` and `casa_distro_admin` are links to `bv`, the `-h` option gets `bv -h`. For these two specific commands that are to be used outside the container, `--` should be added before any option.

**Comment by denisri** [comment]
Right. There must be already something similar for in-container commands, since, for instance, `AimsFileInfo` is also a link to bv, and `AimsFileInfo -h` works as expected.
`bv -h` should only display the doc if it is called as `bv` and not as any other name ?
