### ISSUE TITLE
Capsul soma-workflow variables are not set without manual config editing

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#335]
**Is your feature request related to a problem? Please describe.**

Capsul run command relies on Soma-Workflow env variables `SOMAWF_INPUT_PARAMS` and `SOMAWF_OUTPUT_PARAMS`. But in a remote batch system, these variables do not pass from the job shell to the casa-distro container without a manual config specifying their definition in `/casa/host/conf/casa_distro.json`.
Moreover users usually don't know how to edit this config (and what to set in it).
Plus, in site install the config file can only be personalized in (host) `~/.config/casa-distro/casa_distro3.json` which is still harder to find, and cannot be edited uing the `bv` GUI.

**Describe the solution you'd like**
Maybe define these 2 variables in the default config of Casa-Distro, even if it's not his matter ?

**Comment by ylep** [comment]
I agree that these variables can be passed by default, they are safe and `casa-distro`’s matter is to make things work ;-)

**Comment by denisri** [comment]
I'll do that during environment setup since it's the simplest solution.
