### ISSUE TITLE
Pytorch version shipped with casa-run-5.3 does not support recent GPUs

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#339]
The Deep Convolutional Neural Network sulcus labelling does not work on recent GPUs (such as a NVidia RTX A5000 bought in 2021, which has a NVidia Compute Capability of 8.6). Indeed, PyTorch 1.11.0 that is shipped with casa-run-5.3 only supports up to Compute Architecture 7.0 (i.e. GPUs released before 2020).

```python
>>> import torch.cuda
>>> torch.__version__
'1.11.0+cu102'
>>> torch.cuda.get_arch_list()
['sm_37', 'sm_50', 'sm_60', 'sm_70']
```

I could get it work by upgrading PyTorch to version 1.13.1+cu116:

```
pip install --user -U torch --extra-index-url https://download.pytorch.org/whl/cu116
```
```python
>>> import torch.cuda
>>> torch.__version__
'1.11.0+cu102'
>>> torch.cuda.get_arch_list()
['sm_37', 'sm_50', 'sm_60', 'sm_70']
```

However, that solution does have a very big drawback: the installed size of Pytorch goes from 1.5 GB to 3.5 GB... I don't know how to proceed from here ; I could not find an easy solution for getting the required kernels on-demand for the GPU at hand...

**Comment by denisri** [comment]
I have uploaded new images which include pytorch 1.13.1 (plus other things).
