### ISSUE TITLE
ssh -X does not work with casa_distro

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#40]
The X authorization set up by `ssh -X` seems to be lost when inside the Singularity container. We get the following error : `X11 connection rejected because of wrong authentication.`.

**Comment by sapetnioc** [comment]
This can be reproduced localy by running `ssh -X localhost` and executing any graphical command such as `casa_distro run glxgears`.

**Comment by sapetnioc** [comment]
If I understand well, starting the `ssh -X` session modifies the  `~/.Xauthority` file. Copying this file in the casa_distro home directory while the session is still open removes the authorization error.

**Comment by sapetnioc** [comment]
We may include the copying of the `~/.Xauthority` file in the build workflow home directory each time a command is run (with gui enabled). This could fix this issue. But I do not know what could be the side effects on security or when running several `casa_distro` in parallel.

**Comment by denisri** [comment]
I think we can try that. I think I remember we were doing something similar using docker (mounting the ~/.Xauthority instead of copying it).

**Comment by sapetnioc** [comment]
This issue is fixed in the 3.0 branch.
