### ISSUE TITLE
Add html2text to images

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#41]
In https://github.com/brainvisa/axon/commit/3564d203a005f22f37d94b29d2d35b70c3cd54ed#diff-fadd4ecef900cc0983f2d1c1351d0f6d I have implemented a new way of converting the HTML messages of Axon to plain text (actually Markdown) when they are printed onto the terminal, using [html2text](https://pypi.org/project/html2text/). Moreover, the old approach (kept as fallback) uses the standard `formatter` module, which is now deprecated, so we have to implement a new solution sooner or later.

@brainvisa/release do you agree that I add `python-html2text` and `python3-html2text` to the dev/runtime images?

**Comment by denisri** [comment]
OK for me.
