### ISSUE TITLE
Get rid of Docker ?

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#51]
During the writing of #50, I noticed that a difference between Docker, on the one side, and Singularity and VirtualBox, on the other side, that could make the API and implementation simpler if we get rid of Docker. In the coming changes of v3.0 (yes, I supposed we will increase major version because of API changes)  we will probably no go through Docker anymore for the Singularity image creation (nor for VirtualBox). Therfeore, I think it is a good time for a discussion about keeping Docker or not.

The difference is that Docker does not use files to store images and has its own organization to store them. We already have a way to map Singularity file names and docker images but it was designed as an adaptation to the Docker naming scheme. I think we must work on this mapping with image attributes in mind (image type, system, etc.) and design something specific for Docker naming (to be discussed if we choose to keep Docker). The other problem is that we will need some attributes with images. With Singularity and VirtualBox this will be in a JSON companion file next to an image file. We will have to design something specific for Docker to store/retrieve attributes (probably using image labels). None of these are big problems but I want to be sure we really need Docker before working on it.

**Comment by denisri** [comment]
Personally I'm not using docker images in casa-distro for "real work" every day, but I often use them to test modifications before rebuilding images: as we can use them as root and modify them, we can test apt/pip installs interactively, which is not as simple to do using singularity (we must convert images to writeable directories, which make them "different" images, etc), so I'm not sure about your question.

**Comment by sapetnioc** [comment]
After a few discussions, the current decision for v3.0 is to be able not to use Docker to create Singularity and VirtualBox images but to keep the possibility to create and publish Docker images.

We should also have a closer look to Singularity changes since v3.0 (of Singularity, not casa-distro). The default image extension has changed (*.sif). Does it mean that these new images can be modified ? I think not but I am not sure.
