### ISSUE TITLE
Adapt the organization of /casa ?

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#54]
There are three reasons that make me think we should change slightly the `/casa` organization in v3.0:
- In Ubuntu 18.04 interface in VirtualBox, each mounted directory appear as an icon on the desktop (as well as an entry on file explorer). This can be annoying to have many mounted directories when one is enough. For instance, it would be better to mount a build workflow directory as a single mount point.
- The `/casa` directory contains both image built-in content (such as `environment.sh`) and mounted content (`conf`, `src`, `build`, `home`,`conf`, etc.). It is therefore not possible to mount the whole build workflow directory in `/casa`, every inner directory have to be mounted separately.
- We will need to manage two kind of user directories : the developer kind (the actual build workflow directroy) and the user kind that will contain an install directory but also a `home` and probably a `conf`. In a virtual machine we will only have to mount one of the two kind of directories. This would be great to be able to do this with a single mount also.

Therefore, I think of using the following hierarchy in `/casa`:
```
/casa
├── environment.sh # image built-in
├── host # mounted from host
│   ├── conf
│   ├── home
│   ├── src # exists only for dev environments
│   ├── build # exists only for dev environments
│   ├── install # exists only for run environments
│   ├── tests # optional
├── ... # other optional mounts or built-in directories
```
This proposal is simply adding a level of directory for having a single mount instead of several in standard use cases.

**Comment by denisri** [comment]
This will make paths a little longer for users/developers but I agree on the idea.

**Comment by sapetnioc** [comment]
I started to make some changes in branch 3.0 to implement this new directory organization. This will be tested when creation of new Singularity images is finished.

**Comment by sapetnioc** [comment]
I have a question about this issue. I added a `host` directory in build workflows. This directory is mounted in `/casa/host` in containers. But, to date, there is only the `host` directory in build workflow directory. Should we remove `host` from build workflow directory (we would mount the whole build workflow directory in `/casa/host`) or should we keep the possibility to store files/directories a build workflow level  that are not mounted in container ?

There is a little positive side effect of this new directory : casa_distro v2.* and v 3.* do not see each other build workflows.
