### ISSUE TITLE
Upgrade to pydicom >= 1.0

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#57]
The API of `pydicom` has changed extensively in version 1.0 (notably, the Python package has been renamed from `dicom` to `pydicom`, see this [transition guide](https://pydicom.github.io/pydicom/stable/old/transition_to_pydicom1.html)). We have several packages that depend on the old 0.9.x API in a few spots:

- [aims-free](https://github.com/brainvisa/aims-free) (2 files import `dicom`)
- nuclear_imaging-gpl (13 files import `dicom`)
- nuclear_imaging-private (2 files import `dicom`)
- [soma-io](https://github.com/brainvisa/soma-io) (2 files import `dicom`)
- [soma-io-gpl](https://github.com/brainvisa/soma-io-gpl) (1 file imports `dicom`)
- qualicati (**how many files import `dicom`?**)

[list updated on 7 October 2020]

As the old version 0.9.x is not maintained anymore since January 2017, we would like to migrate to a more recent version (pydicom >= 1.2.1). ~We need to coordinate this change because it seems that both versions cannot be installed simultaneously.~

We will probably try to organize a sprint in order to coordinate the migration.

**Comment by sapetnioc** [comment]
Should we target casa-distro 3.0 for this change or must we make it earlier ? If I can go on working on 3.0, I guess it could be ready in july 2020. But remember that this 3.0 version will be incompatible with older versions. It will be necessary to upgrade Singularity (>= 3.5), to download new image (new way of building images and new Singularity format) and to create new build workflow (new directory structure in build workflow).

**Comment by rbonicel** [comment]
Regarding qualicati, I tried updating pydicom to the latest release, 2.0.0, and running it in a casa_distro with Python3. 
It went very easily with a `pip upgrade --user` on current casa_distro build workflow.
I changed all the `import dicom` and derivatives (there where lots of them in all qualicati-related scripts). I found no compatibility problems between pydicom 2.0.0 and the Python3 Singularity image so far. I have yet to commit my changes on svn.

**Comment by Hboni** [comment]
The biggest problem is that pydicom 2.0 drops the compatibility for python2, so if we want to keep compatibility with python2 it's not the best choice !?

**Comment by rbonicel** [comment]
Changed to previous version 1.4.2, which keeps compatibility Python2/Python3 . I will continue the tests from there.

**Comment by sapetnioc** [comment]
Can this issue be closed ?

**Comment by Hboni** [comment]
I would say no but soon, a more recent version of pydicom has bees tested by the ICM team.
Furthermore, pydicom has to be updated for casa-distro 3.0? For now, I didn't change all the `dicom` import in `nuclear-imaging` projects.

**Comment by Hboni** [comment]
I found an issue when we tried to use recent PET dicom from a center, with an `unknown encoding: ISO 2022 IR 100`.
Using pydicom 1.2.1 solve the problem.

@ylep said

> We need to coordinate this change because it seems that both versions cannot be installed simultaneously.

But on my casa_distro (2) image, ubuntu-18.04, python3 I can import pydicom v1.2.1, and import dicom v0.9.9

**Comment by sapetnioc** [comment]
Pydicom does not seem to be installed on 3.0 images : `import pydicom` does not work. But `import dicom` works and says that version is 0.9.9. Is it the same package with a change in imports ?

Should we upgrade to a more recent version ? If yes can it be done quickly or does someone need time to adapt code ?

**Comment by sapetnioc** [comment]
I should have read the comments more carefully. If Python 2 is not supported we must stay in this version for the next release. This issue will be closed only in two releases.

**Comment by Hboni** [comment]
I didn't react in time, after reading comments, I just want to add that we can "safely" change pydicom version to 1.4.2, to keep compatibility with python2 in casa-distro image. Pydicom drops compatibility with python only at 2.0.0.
