### ISSUE TITLE
Remove p3q5 image

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#58]
The `p3q5` image is not used as far a I know, and anyway it is not really maintained. Considering that we will have to make a Python3-only release in Ubuntu 20.04, maybe we can get rid of `p3q5` now and test a Python3, Qt5-only system in the future `ubuntu-20.04` images?

**Comment by denisri** [comment]
I quite agree but as I did not make and maintain it myself, let's ask Yann.

**Comment by sapetnioc** [comment]
Yes. I did this image for the migration script but it was never used.
