### ISSUE TITLE
The software-only libGL causes issues of transparent windows with Intel graphics chipsets

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#59]
Removing `/usr/local/lib/libGL.so.1` and `/usr/local/lib/libglapi.so.0` restores correct rendering on an Intel chipset.

It could be that this issue is due to the `--disable-egl` and `--disable-gbm` compilation options of the software-only libmesa:
https://github.com/brainvisa/casa-distro/blob/5a6d70c73ab062a517e0a810e9d6887fafbd76a2/share/docker/casa-dev/ubuntu-16.04/build_mesa.sh#L14

However, given that the system version of mesa works fine in most cases, and considering that the software-only mesa is a mere workaround for a rather obscure case (running a GUI app on a machine with a NVidia driver where the user does not have permission to access `/dev/nvidiactl`, e.g. over SSH), I would argue that we should put the software-only libmesa in the library path *only* if explicitly requested, or if the specific situation that warrants the workaround is detected.

**Comment by denisri** [comment]
I agree with the manual activation, but I have no clear idea on how to activate it. In the current state, it works well with nvidia drivers because singularity places them first in the paths, but as you point out this behaviour is not the same with other drivers. Anyway we probably missed some options in the compilation of the software libGL because if it really performs software-only rendering, it should work (slowly) in any case, and it doesn't seem to.
I don't know if there is a way to integrate with libGLdispatch which is now currently used on linux distribs to switch between several GL implementations depending on the driver. This is probably difficult to setup.

**Comment by ylep** [comment]
This issue should be fixed in casa-distro 3.0 (upcoming Brainvisa 5.0 release) because we are not shipping the old software-only libGL anymore.

**Comment by denisri** [comment]
Trying to recompile a libGL (version 18.2.2 same as ubuntu 18.04) I get the exact same behaviour as we already had: transparent rendering... enabling DRI + swrast also results in "libGL error: failed to load driver: swrast", same as using the system opengl.
Still trying...

**Comment by denisri** [comment]
After many recompilations of mesa using many different config options, I could not make it work better.
Then I just find this:
https://bugzilla.redhat.com/show_bug.cgi?id=589802
actually setting `XLIB_SKIP_ARGB_VISUALS=1` fixes the problem.
So we may need to add this variable to the env at casa-distro startup (possibly optionally in the casa_distro.json file).

**Comment by denisri** [comment]
What's the right place for that ?
* run option:
  - [-] the option needs to be added manually at each run command, whereas we want it to be simple for users
  - [-] the mechanism under the option is hard-coded and cannot be changed depending on user config / hardware / OS
  - [+] if casa-distro is updated, all existing environments will benefit from changes / fixes / improvements
* config option:
  - [-] cannot be changed / fixed via an update after the environment is created
  - [+] persistent: once correctly setup, the user gets the right config every time
  - [+] can be setup according to the user environment and needs

I don't have a strong opinion about it but I think I somewhat prefer the 2nd solution right now.

**Comment by sapetnioc** [comment]
I prefer the first option with the ability to define the default value for
some run options in the config file. I can easily add this feature.
