### ISSUE TITLE
/tmp may be reused during image creation

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#60]
If the shell scripts used to build images are used to build singularity image (without going through Docker), they all use the same /tmp (the host one) by default. But some scripts are creating hard-coded directories in /tmp. Therefore, there can be two problems :
1. If a previous script was interrupted, the directory was not removed and the current script fail to create the directory.
1. It is not possible to run two scripts in parallel without risking a race condition if they both write in the same directory.

I propose to use an environment variable such as `$TMP` instead of `/tmp` in the scripts. It will be the responsibility of the script caller to set is to an appropriate value. This value could be `/tmp` for Dockerfiles or a brain new temporary directory managed by `casa_distro_admin` (and removed even if the script is interrupted) for Singularity.

**Comment by denisri** [comment]
OK. A new temp directory would be perfect (maybe with an option to keep it without removing in case of debug).
