### ISSUE TITLE
Use Python 3 by default in casa_distro 3.0

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#64]
I propose to make compilation of distro to use Python 3 by default in casa_distro 3.0 by adding the following line in `bv_maker.cfg` files :

```cmake_options = -DPYTHON_EXECUTABLE=/usr/bin/python3```

**Comment by denisri** [comment]
OK for me.

**Comment by ylep** [comment]
This change makes Python 3 the default for all systems, doesn’t it? I thought that we had agreed on this plan:

- keep Python 2 by default for the `ubuntu-18.04` images and make the next release of BrainVISA  based on this (this is why I have only included Python 2 / Qt 5 in the `casa-run` images);

- switch to Python 3 for the upcoming `ubuntu-20.04` images (considering that many Python packages are _only_ available for Python 3 in that release of Ubuntu, we need to drop support for Python 2).

If we stick to this plan, then `-DPYTHON_EXECUTABLE` is not needed.

**Comment by denisri** [comment]
Oh yes, you're right.

**Comment by sapetnioc** [comment]
Ok, let's keep it as it is then.
