### ISSUE TITLE
Create the 3.0 user environment

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#66]
For the future container/virtual machine BrainVISA distribution system, we must have a working and documented user environment.

**Comment by sapetnioc** [comment]
I have a question. What Python and Qt versions will we use for next release ? I would say Python 3 / Qt 5 but I have the feeling that the runtime image defined in the `runtime_image` branch is tested for Python 2. For instance, `numpy` is not installed on Python 3.

**Comment by denisri** [comment]
Actually I wished we had a release sooner, and I was in the idea that it would still be with python2 (because I'm not sure all the code and all projects are ready yet for python3). But it seems that we are unable to release in the near future, so I don't know...
