### ISSUE TITLE
End user commands for admins, developers and users

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#67]
In casa_distro 3.0, we will provide two kind of environments: *run* and *dev*. We will target three kind of users: scientists, developers and admins. This will require to adapt the user commands. Here is a summary of the various commands that are planned for v3.0. To be discussed.

- `casa_distro setup` : allows to configure a new run or dev environment. This is the first thing any casa_distro user will have to do. This is the replacement of `casa_distro create`.
- `casa_distro update` : update one or several run environments. This command allows to update virtual images as well as environment directory content if any change was published.
- `casa_distro bv_maker` : update and/or build one or several dev environments
- `casa_distro list` : list configured environments and/or available virtual images
- `casa_distro run` : execute a command in a single environment
- `casa_distro mrun` : execute a command in one or several environments
- `casa_distro writable` : allow a selected environment to be writable (eventually generating a writable Singularity image).
- `casa_distro root` : start a shell with root privileges in a container. Especially useful with writable images.
- `casa_distro clean`: allow to delete unused virtual images
- `casa_distro_admin build_image` : build a virtual image, either a system, run or dev one. 
- `casa_distro_admin publish_image` : publish an image in order to make it avaiable to `casa_distro update`
- `casa_distro_admin setup_env` : setup a standard dev or run environment. This will call `casa_distro setup` but some may have specific naming, metadata or content checking.
- `casa_distro_admin build_env` : build a standard dev or run environment. This will call `casa_distro bv_maker` for dev environment. For run environment this will mainly call ̀`make install-runtime` from a standard dev environment. This command may use specific naming, metadata or content checking.
- `casa_distro_admin publish_env`: publish a run environment (may be used for dev environments if we decide to publish them).

**Comment by denisri** [comment]
This looks OK for me.

**Comment by sapetnioc** [comment]
Even if there are a few differences in commands, I was able to create run, dev, and user images in Singularity and VirtualBox. I think this issue can be closed.
