### ISSUE TITLE
Can't run brainvisa with default config

### ISSUE THREAD

**Issue by Hboni** [brainvisa/casa-distro#69]
I created a new build workflow in casa-distro with those parameters : 
- branch : bug_fix
- distro_source : cati_platform
- system : ubuntu-18.04
I updated the image also.

I ran bv_maker without changing anything in bv_maker.cfg without real problems, but I cannot run brainvisa with it.

```
~$ casa_distro -r casa_distro_18/ run distro=py2_qt4 brainvisa
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-hb261775'
Loading toolbox catidb
Loading toolbox cortical_surface
Loading toolbox data management
Loading toolbox datamind
Loading toolbox freesurfer
Loading toolbox longitudinal_pipelines
Loading toolbox morphologist
Loading toolbox nuclearimaging
Loading toolbox sacha
Loading toolbox spm
Loading toolbox structural_analysis
Loading toolbox tools
Loading toolbox viewers
Loading toolbox whasa_v2
Loading toolbox My processes
soma-workflow starting in light mode
Workflow controller initialised
The log file for this session is '/casa/home/.brainvisa/brainvisa3.log'Database /casa/build/share/brainvisa-share-4.6 must be updated because there is
no database file./usr/local/lib/python2.7/dist-packages/dicom/__init__.py:53: UserWarning: 
This code is using an older version of pydicom, which is no longer 
maintained as of Jan 2017.  You can access the new pydicom features and API 
by installing `pydicom` from PyPI.
See 'Transitioning to pydicom 1.x' section at pydicom.readthedocs.org 
for more information.

  warnings.warn(msg)
FSL Siena could not be found. Please fill BrainVISA preferences to use "SIENA - Halfway Coregistration" process.
Warning: pyaimsgui not available
Matlab or SPM8 Standalone paths are not found
Segmentation fault
Traceback (most recent call last):
  File "/usr/local/bin/casa_distro", line 30, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/casa_distro/command.py", line 167, in main
    result = command(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/casa_distro/user_commands.py", line 346, in run
    conf=conf)
  File "/usr/local/lib/python2.7/dist-packages/casa_distro/build_workflow.py", line 525, in run_container
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/casa_distro/singularity.py", line 235, in run_singularity
    check_call(singularity, env=container_env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['singularity', 'run', '--cleanenv', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/cati/qualicati/save:/cati/qualicati/save', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/cati/qualicati/database_debug:/cati/qualicati/database_debug', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/custom/build:/casa/custom/build', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/build:/casa/build', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/conf:/casa/conf', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/install:/casa/install', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/src:/casa/src', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/tests:/casa/tests', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/custom/src:/casa/custom/src', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/pack:/casa/pack', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/home:/casa/home', '--bind', u'casa_distro_18/py2_qt4/bug_fix_ubuntu-18.04/cati/qualicati/database:/cati/qualicati/database', u'--pwd', u'/casa/home', u'casa_distro_18/cati_cati_platform_ubuntu-18.04.simg', 'brainvisa']' returned non-zero exit status 139
```

**Comment by sapetnioc** [comment]
I am trying to reproduce the problem. It will take a while to download image and build the whole system.

**Comment by sapetnioc** [comment]
I can reproduce the bug. It also crash in batch mode. gdb adds the following info :
```Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fff24d94cfe in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtCore.x86_64-linux-gnu.so
```

**Comment by sapetnioc** [comment]
There is also this message that seem not normal : Warning: pyaimsgui not available
I think it is more an Axon or Aims issue than a casa-distro one.
There is an error in the module loader usage :
```In [1]: from soma.aims import aimsgui
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c6373d18da9b> in <module>()
----> 1 from soma.aims import aimsgui

/casa/build/python/soma/aims/aimsgui.py in <module>()
     35 from soma.importer import ExtendedImporter
     36 ExtendedImporter().importInModule('', globals(), locals(),
---> 37                                   'aimsguisip', ['aimsguisip'])
     38 ExtendedImporter().importInModule( 'soma.aims', globals(), locals(),
     39                                   'aimsguisip', ['aimssip.aims'] )

/casa/build/python/soma/importer.pyc in importInModule(self, moduleName, globals, locals, importedModuleName, namespacesList, handlersList, *args, **kwargs)
     97         # __builtin__.__import__ is not supported
     98         importedModule = importlib.import_module('.' + importedModuleName,
---> 99                                                  package)
    100         sys.modules[importedModuleName.split('.')[-1]] = importedModule
    101 

/usr/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

ImportError: No module named aimsguisip
```
But aimsguisip could be loaded :
```In [1]: from soma.aims import aimsguisip

In [2]: 
```

**Comment by denisri** [comment]
Which version of Qt are you using ?
On Ubuntu 18 we are using Qt5 by default (unless forced in the config), and here the segfaut occurs in PyQt4. So I guess both Qt4 and Qt5 get loaded at the same time, which results in a crash.

One more thing: `/usr/lib/python2.7/dist-packages/PyQt4/QtCore.x86_64-linux-gnu.so` is a binary version of Qt4 installed via pip: it is not the system (Ubuntu 18.04) version of Qt, and is not compatible with it when compiling Qt bindings. In `casa-distro/master` we were using a script to build and install PyQt from sources to avoid this problem (and others). This custom install of PyQt (both 4 and 5) was needed to avoid a bug in sip (thus we needed to use a different PyQt from the system), but was using the system Qt. I strongly recommend *not* installing any PyQt via pip: it will always cause crashes in pyaims/pyanatomist etc because the latter are not built using this Qt.

Now the other question is: why is PyQt4 loaded when we are building using Qt5/PyQt5 ?
`soma.qt_gui.qt_backend` tries to detect and load the _right_ version of PyQt. For this, it looks if a PyQt module is already loaded: if pyaims is imported, it should have loaded the version it's compiled with. If pyaims is not loaded yet, we are using the "standard" method (also used by ipython, matplotlib and other software) based on the `QT_API` env variable. This variable is set by bv_env so that it matches the build. So I suspect there is a problem in bv_maker config somewhere. Can you please check that in the `CMakeCache.txt` ?
Or maybe somewhere in the code, `soma.qt_gui.qt_backend` is not used but `PyQt4` is imported directly ?

**Comment by sapetnioc** [comment]
There is nothing about Qt in `bv_maker.cfg` but `CMakeCache.txt` is configured for Qt 5. There is probably a problem with the official `cati_platform` image. At least we know where to investigate.

**Comment by denisri** [comment]
Qt version defaulting to Qt5 on Ubuntu 18.04 is specified in brainvisa-cmake (cmake/specific settings) thus not needed in `bv_maker.cfg`.
You can run `bv_env` and see if there is a `QT_API` variable in its output. For me I have:
`export QT_API='pyqt5'`

**Comment by sapetnioc** [comment]
I have the same QT_API with bv_env. I will investigate the image
installation but there is nothing except "apt get" in casa_distro
Dockerfile. So, if there is a pip installation of PyQt it may be also in
casa-dev image.

**Comment by sapetnioc** [comment]
It seems that the QtCore file is a system one :
```
Singularity> dpkg -S /usr/lib/python2.7/dist-packages/PyQt4/QtCore.x86_64-linux-gnu.so 
python-qt4: /usr/lib/python2.7/dist-packages/PyQt4/QtCore.x86_64-linux-gnu.so
```

**Comment by sapetnioc** [comment]
I found a suspect. In sacha and whasa, there are processes with direct PyQt4 import :
```
Singularity> grep --include='*.py' -R PyQt4
toolboxes/whasa_v2/processes/pywhasa_v2-components/qc_auto_for_pyWHASA_v2.py:from PyQt4     import Qt
toolboxes/whasa_v2/processes/whasa_v2-components/qc_auto_for_WHASA_v2.py:from PyQt4     import Qt
toolboxes/sacha/processes/lsacha/qc_auto_SACHA_long_moy.py:from PyQt4 import Qt
toolboxes/sacha/processes/lsacha/qc_auto_SACHA_long.py:from PyQt4 import Qt
toolboxes/sacha/processes/tools/qc_auto_SACHA_atlas.py:from PyQt4 import Qt
toolboxes/sacha/processes/sacha/qc_auto_SACHA.py:from PyQt4 import Qt
```

**Comment by Hboni** [comment]
Sacha and Whasa are not even in python3, but in my casa-distro ubuntu-18.04 python3, import errors appear for PyQt4 when I launch brainvisa, but brainvisa launched anyway, not sure that's the problem ...

**Comment by sapetnioc** [comment]
Well, if I remove Sacha and Whasa toolboxes there is no more segfault. I'm all for the presumption of innocence, but these two have good guilty faces.

**Comment by sapetnioc** [comment]
For me the issue is closed because it should go to Sacha, Whasa or Axon maybe.

**Comment by denisri** [comment]
Oh sorry yes this is actually the Qt bindings lib. The system one. But there is a bug in the system sip/PyQt on Ubuntu 18, so we should avoid it.
that's weird, on casa-distro/master it seems that PyQt4 is not installed at all (which may make sense because there are also some missing parts in PyQt4 (WebKit) which makes it impossible to use for our needs).
