### ISSUE TITLE
Change branch names in 3.0 ?

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#72]
In version 2.*, branches are named `latest_release`, `bug_fix` and `trunk`. This is an Subversion convention. Since we plan to have a majority of our projects in Git, we could use the API change of version 3.0 to use `latest_release`, `master` and `integration`.

**Comment by denisri** [comment]
Yes, I agree. This probably needs a modif in brainvisa-cmake projects list, and possibly a manual update for developers (not sure about that) but I'm OK for it.
