### ISSUE TITLE
Create a system with only Python 3 and Qt5

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#8]
This system will be the future Python 3 only default system. Container images are going to be smaller than ones including both Python 2 and Python 3. During the transition and tests of main projects in Python 3, there will be a new `system` called `p3q5` based on a recent Ubuntu version (it will be Ubuntu 20.04 when it is released but Ubuntu 19.10 until then).

**Comment by sapetnioc** [comment]
I started the image creation test with Ubuntu 19.04. The `gadfly` package is missing, we must find a solution for `datamind`.

**Comment by sapetnioc** [comment]
Another missing package : `x11proto-print-dev` I do not know yet what it was used for.

**Comment by sapetnioc** [comment]
Another missing package : `libarmadillo8`

**Comment by ylep** [comment]
Done in 18a015a3bfa80cda8e601cd48adcc8fc523cbcd1
