### ISSUE TITLE
Add tests in release creation workflows

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#81]

**Comment by sapetnioc** [comment]
I need to know the status of this issue in order to manage the switch to a new organization and management of Jenkins server. Jenkins management had been rewritten and there is [a pull request in brainvisa_cmake](https://github.com/brainvisa/brainvisa-cmake/pull/64) to implement this change. With the new organization, there is a link between the test results and `casa-distro` via the name of the environment used to perform the tests. We must take this into account for this issue.

**Comment by sapetnioc** [comment]
Related to this issue but with wider scope, see #157

**Comment by sapetnioc** [comment]
I am trying to understand and test how tests are working in order to make the BrainVISA Build Infrastructure documentation. 

I am starting with `bv_maker` only. If I understand well, one must call `bv_maker testref` at least once (and when it is necessary to rebuild reference test data)  and then call `bv_maker test` to perform tests. The data generated by `testref` is going into a directory whose location is in `test_ref_data_dir` entry of section `[build]` of `bv_maker.cfg`. The directory for data generated by tests is in `test_run_data_dir` of the same section. Am I missing something at that point ?

**Comment by sapetnioc** [comment]
Going on on my investigation on tests I have a new question : should we delegate to casa-distro the actual execution and report of testing commands ? I found out that, via `ctest` and `bv_env_test`, it is fairly easy to extract the tests commands that need to be run for a single step (steps are defined in `ctest --print-labels`, e.g. aims, axon, highres-cortex, etc.). This work could be done by `bv_maker` as part of the build process. The build would then produce, a list of test steps and the corresponding commands to run (or we could have a dedicated `bv_maker`command for that). These could be used by `casa_distro` to perform the tests and log the results (eventually on Jenkins) in any environment (dev or user, singularity or VirtualBox) without having to use ssh or singularity in singularity. This is not a lot of work but it is a big change in our organization. Is this a wrong way ?

**Comment by denisri** [comment]
> I am trying to understand and test how tests are working in order to make the BrainVISA Build Infrastructure documentation.
> 
> I am starting with `bv_maker` only. If I understand well, one must call `bv_maker testref` at least once (and when it is necessary to rebuild reference test data) and then call `bv_maker test` to perform tests. The data generated by `testref` is going into a directory whose location is in `test_ref_data_dir` entry of section `[build]` of `bv_maker.cfg`. The directory for data generated by tests is in `test_run_data_dir` of the same section. Am I missing something at that point ?

As far as I remember, yes, that's it.
mv_maker also had testref_pack and test_pack to test installed packages, but this part is obviously obsolete now we have casa-distro, and it was done in a cuisine-bidouille way (using the ctest/makefiles from a build tree to run programs from an installed distribution).

**Comment by denisri** [comment]
> Going on on my investigation on tests I have a new question : should we delegate to casa-distro the actual execution and report of testing commands ? I found out that, via `ctest` and `bv_env_test`, it is fairly easy to extract the tests commands that need to be run for a single step (steps are defined in `ctest --print-labels`, e.g. aims, axon, highres-cortex, etc.). This work could be done by `bv_maker` as part of the build process. The build would then produce, a list of test steps and the corresponding commands to run (or we could have a dedicated `bv_maker`command for that). These could be used by `casa_distro` to perform the tests and log the results (eventually on Jenkins) in any environment (dev or user, singularity or VirtualBox) without having to use ssh or singularity in singularity. This is not a lot of work but it is a big change in our organization. Is this a wrong way ?

Not sure I would want to disable the test feature in bv_maker (which still can work outside of casa-distro), but the idea to write test script(s) running tests in the environment we choose (in bv_maker or not, in a container or not, using a build tree or an installed distribution in another container) is really interesting, and is probably the good answer to the above issue of cuisine-biduille we used to use ;)
So I say: Yes.

**Comment by sapetnioc** [comment]
The good thing is that I would not disable anything (except obsolet pack related commands but that is another story). I will make another issue to explain the feature I have in mind.
