### ISSUE TITLE
Modify website for casa-distro 3 / BrainVISA 5

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#83]

**Comment by Hboni** [comment]
- [ ] create VirtualBox instructions
- [ ] update links to new builds (singularity, virtualbox)
- [ ] update build workflow organisation description (directory organization and mount points)

**Comment by denisri** [comment]
@Hboni I think you can (or even should) merge your branch documentation_3.0 into branch 3.0, it will be easier to synchronize / test, and as it is "only" documentation there is no risk to break things for other developers.

**Comment by Hboni** [comment]
I agree, it was not a good idea to separate documentation from the 3.0 branch.

**Comment by denisri** [comment]
Is it OK ? It doesn't look like a merge - did you copy the files manually ?
If it's OK we can remove the branch documentation_3.0

**Comment by denisri** [comment]
Oh sorry I didn't see  #134 but gitg doesn't show it to me as a merge (!)

**Comment by denisri** [comment]
I have modified the download.rst page in the web site doc. Now we need the tables to display available downloads in the php script.

**Comment by denisri** [comment]
Done. Does it seem OK ?

**Comment by denisri** [comment]
We should also change all links http://brainvisa.info -> https://brainvisa.info

**Comment by denisri** [comment]
Change contact page for forum / github discussions

**Comment by denisri** [comment]
change brainvisa.github.io for users - discussions will be there

**Comment by denisri** [comment]
I opened issues #225, #226 and #227 for the items cited above

**Comment by denisri** [comment]
It's good enough for me now...

**Comment by denisri** [comment]
The links to older packages (4.6.x and earlier) have been broken on the new web site. The page displays an empty table because the source code and files (`bv_build_web_downloadpage.py` etc) have been deleted from the sources.
Do totally we remove access to older versions, or should we repair the links ?
