### ISSUE TITLE
Perform tests on Linux for various Workflows

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#84]
Workflows to be tested:

- [x] Single user, single machine install of casa-distro on a CEA-installed machine

- [x] Shared casa-distro install on a CEA network drive (e.g. `/i2bm/brainvisa`)

**Comment by denisri** [comment]
_bbi_ tests have just passed (see the [Jenkins server](https://new.brainvisa.info/builds/)) both for builds and the installed singularity image.
anatomist, morphologist-ui, brainvisa user interfaces are OK on linux/singularity.

**Comment by sapetnioc** [comment]
Champagne 🍾 !

**Comment by denisri** [comment]
I have installed a shared environment in `/i2bm/brainvisa/brainvisa-5.0.0-test11` from the `a-sac-ns-brainvisa` user.
From my own user account I could run it, add mount points for myself using the config GUI, and use the commands. So I guess shared environments are OK now.

**Comment by denisri** [comment]
The same shared install run from a Mac host also worked OK.
