### ISSUE TITLE
User-specific home in v3.0

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#99]
`home` has moved into `/casa/host/home` and does not have a specific mount point anymore (used to be `/casa/home`). However, when we use a user-specific HOME (introduced in https://github.com/brainvisa/casa-distro/pull/93), we really need to mount it separately.

In order to avoid nesting the mount points (I am not sure if it works at all), I suggest to bring it back to `/casa/home`.

**Comment by denisri** [comment]
I haven't followed the discussion closely, but why needs a user-specific HOME to be mounted separately ?

**Comment by ylep** [comment]
In casa-distro 3.0 the directory structure is currently as follows on the host system:

```
<environment_dir>
├── conf
│   ├── casa_distro.json
│   └── svn.secrets
└── host
    ├── home
    └── src, build...
```

And `<environment_dir>/host -> /casa/host` is the only mount that is done in the container.

In the user-specific home scenario, the `home` directory cannot be a sub-directory of `host`, so my suggestion is that we separate it from `host`: mount `<environment_dir>/home -> /casa/home` in the non-user-specific-home scenario, and mount `/home/<user>/.config/casa-distro/.../home -> /casa/home` in the user-specific-home scenario.

**Comment by denisri** [comment]
Is /casa/home hard-coded anywhere, or could we use $HOME instead ?
